apiVersion: v2
name: arc-runner-set
type: application

# this version number should be incremented each time you make changes
# to the chart and its templates, including the app version.
# is expected to follow semantic versioning!
version: 1.0.0

# this is the version number of the application being deployed
# should be incremented each time you make changes to the application
appVersion: "1.0"

dependencies:
- name: gha-runner-scale-set
  version: 0.9.3
  repository: oci://ghcr.io/actions/actions-runner-controller-charts
