# yaml-language-server: $schema=https://raw.githubusercontent.com/datreeio/CRDs-catalog/refs/heads/main/cert-manager.io/certificate_v1.json
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: sonarr-swifthomelab-net
  namespace: cert-manager
spec:
  secretName: sonarr-swifthomelab-net
  issuerRef:
    name: swifthomelab-net-issuer
    kind: ClusterIssuer
  commonName: sonarr.swifthomelab.net
  dnsNames:
  - sonarr.swifthomelab.net
