# yaml-language-server: $schema=https://raw.githubusercontent.com/datreeio/CRDs-catalog/refs/heads/main/projectcontour.io/httpproxy_v1.json
apiVersion: projectcontour.io/v1
kind: HTTPProxy
metadata:
  name: sonarr-ingress
  namespace: sonarr
spec:
  virtualhost:
    fqdn: sonarr.swifthomelab.net
    tls:
      secretName: cert-manager/sonarr-swifthomelab-net
  routes:
  - services:
    - name: sonarr
      port: 8989
---
# yaml-language-server: $schema=https://raw.githubusercontent.com/datreeio/CRDs-catalog/refs/heads/main/projectcontour.io/httpproxy_v1.json
apiVersion: projectcontour.io/v1
kind: HTTPProxy
metadata:
  name: sonalt-ingress
  namespace: sonarr
spec:
  virtualhost:
    fqdn: sonalt.swifthomelab.net
    tls:
      secretName: cert-manager/sonalt-swifthomelab-net
  routes:
  - services:
    - name: sonalt
      port: 8989
