apiVersion: projectcontour.io/v1
kind: HTTPProxy
metadata:
  name: sonarr-ingress
  namespace: sonarr
spec:
  virtualhost:
    fqdn: sonarr.swifthomelab.net
    tls:
      secretName: cert-manager/sonarr-swifthomelab-net
  routes:
  - services:
    - name: sonarr
      port: 8989
