apiVersion: v1
kind: Service
metadata:
  name: sonarr
  namespace: sonarr
  labels:
    app: sonarr
    app.kubernetes.io/name: sonarr
spec:
  type: ClusterIP
  publishNotReadyAddresses: false
  ports:
  - name: http
    port: 8989
    protocol: TCP
    targetPort: 8989
  selector:
    app.kubernetes.io/name: sonarr
