apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: overseerr-swifthomelab-net
  namespace: cert-manager
spec:
  secretName: overseerr-swifthomelab-net
  issuerRef:
    name: swifthomelab-net-issuer
    kind: ClusterIssuer
  commonName: overseerr.swifthomelab.net
  dnsNames:
  - overseerr.swifthomelab.net
  - request.swifthomelab.net
