apiVersion: projectcontour.io/v1
kind: TLSCertificateDelegation
metadata:
  name: overseerr-swifthomelab-net
  namespace: cert-manager
spec:
  delegations:
  - secretName: overseerr-swifthomelab-net
    targetNamespaces:
    - overseerr
