apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: proxmox-csi-plugin
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "0"
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: csi-proxmox
    server: https://kubernetes.default.svc
  project: default
  source:
    path: apps/proxmox-csi-plugin
    repoURL: https://github.com/JosBritton/cd.git
    targetRevision: HEAD
  syncPolicy:
    managedNamespaceMetadata:
      labels:
        pod-security.kubernetes.io/enforce: privileged
    syncOptions:
    - CreateNamespace=true
