apiVersion: "argoproj.io/v1alpha1"
kind: "Application"
metadata:
  name: "vaultwarden"
  namespace: "argocd"
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
  finalizers:
    - "resources-finalizer.argocd.argoproj.io"
spec:
  destination:
    namespace: "vaultwarden"
    server: "https://kubernetes.default.svc"
  project: "default"
  source:
    path: "vaultwarden"
    repoURL: "https://github.com/JosBritton/cd.git"
    targetRevision: "HEAD"
  syncPolicy:
    syncOptions:
      - "CreateNamespace=true"
