apiVersion: projectcontour.io/v1
kind: TLSCertificateDelegation
metadata:
  name: grafana-swifthomelab-net
  namespace: cert-manager
spec:
  delegations:
  - secretName: grafana-swifthomelab-net
    targetNamespaces:
    - prometheus-operator
