# yaml-language-server: $schema=https://raw.githubusercontent.com/yannh/kubernetes-json-schema/refs/heads/master/master/service-v1.json
apiVersion: v1
kind: Service
metadata:
  name: graphite-exporter
  labels:
    app.kubernetes.io/name: graphite-exporter
    app.kubernetes.io/instance: graphite-exporter
  namespace: prometheus-operator
spec:
  type: NodePort
  ports:
  - name: graphite
    port: 30910
    targetPort: 9109
    nodePort: 30910
    protocol: TCP
  - name: graphite-udp
    port: 30910
    targetPort: 9109
    nodePort: 30910
    protocol: UDP
  selector:
    app.kubernetes.io/name: graphite-exporter
    app.kubernetes.io/instance: graphite-exporter
---
# yaml-language-server: $schema=https://raw.githubusercontent.com/yannh/kubernetes-json-schema/refs/heads/master/master/service-v1.json
apiVersion: v1
kind: Service
metadata:
  name: graphite-exporter-metrics
  labels:
    app: graphite-exporter
    app.kubernetes.io/name: graphite-exporter
    app.kubernetes.io/instance: graphite-exporter
  namespace: prometheus-operator
spec:
  type: ClusterIP
  publishNotReadyAddresses: false
  ports:
  - name: metrics
    port: 9108
    protocol: TCP
    targetPort: 9108
  selector:
    app.kubernetes.io/name: graphite-exporter
    app.kubernetes.io/instance: graphite-exporter
