# yaml-language-server: $schema=https://raw.githubusercontent.com/datreeio/CRDs-catalog/refs/heads/main/projectcontour.io/httpproxy_v1.json
apiVersion: projectcontour.io/v1
kind: HTTPProxy
metadata:
  name: grafana-ingress
  namespace: prometheus-operator
spec:
  virtualhost:
    fqdn: grafana.swifthomelab.net
    tls:
      secretName: cert-manager/grafana-swifthomelab-net
  routes:
  - services:
    - name: prometheus-operator-grafana
      port: 80
