# yaml-language-server: $schema=https://raw.githubusercontent.com/datreeio/CRDs-catalog/refs/heads/main/monitoring.coreos.com/prometheusrule_v1.json
apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: provisioned-recording-rules-extra
  namespace: prometheus-operator
  labels:
    release: prometheus-operator
spec:
  groups:
  - name: extra-provisioned.rules
    interval: 15s
    rules:
    - record: namespace:container_cpu_usage_seconds:sum_rate1m
      labels: {}
      expr: >-
        sum by (namespace) (rate(container_cpu_usage_seconds_total{image!=""}[1m]))
        + on (namespace)
          (
            sum by (namespace) (
                  rate(windows_container_cpu_usage_seconds_total{container_id!=""}[1m])
                * on (container_id) group_left (container, pod, namespace)
                  max by (container, container_id, pod, namespace) (
                    kube_pod_container_info{container_id!=""}
                  )
              or
                kube_namespace_created * 0
            )
          )
    - record: namespace:container_memory_working_set_bytes:sum
      expr: >-
        sum by (namespace) (container_memory_working_set_bytes{image!=""})
        + on (namespace)
          (
            sum by (namespace) (
                  windows_container_memory_usage_commit_bytes{container_id!=""}
                * on (container_id) group_left (container, pod, namespace)
                  max by (container, container_id, pod, namespace) (
                    kube_pod_container_info{container_id!=""}
                  )
              or
                kube_namespace_created * 0
            )
          )
    - record: namespace:container_fs_writes_bytes:sum_rate5m
      expr: >-
        sum by (namespace) (
          rate(
            container_fs_writes_bytes_total{container!="",device=~"(/dev/)?(mmcblk.p.+|nvme.+|rbd.+|sd.+|vd.+|xvd.+|dm-.+|md.+|dasd.+)",job="kubelet",metrics_path="/metrics/cadvisor",namespace!=""}[5m]
          )
        )
    - record: namespace:container_fs_reads_bytes:sum_rate5m
      expr: >-
        sum by (namespace) (
          rate(
            container_fs_reads_bytes_total{container!="",device=~"(/dev/)?(mmcblk.p.+|nvme.+|rbd.+|sd.+|vd.+|xvd.+|dm-.+|md.+|dasd.+)",job="kubelet",metrics_path="/metrics/cadvisor",namespace!=""}[5m]
          )
        )
    - record: namespace:container_fs_writes_bytes:sum_irate1m
      expr: >-
        sum by (namespace) (
          irate(
            container_fs_writes_bytes_total{container!="",device=~"(/dev/)?(mmcblk.p.+|nvme.+|rbd.+|sd.+|vd.+|xvd.+|dm-.+|md.+|dasd.+)",job="kubelet",metrics_path="/metrics/cadvisor",namespace!=""}[1m]
          )
        )
    - record: namespace:container_fs_reads_bytes:sum_irate1m
      expr: >-
        sum by (namespace) (
          irate(
            container_fs_reads_bytes_total{container!="",device=~"(/dev/)?(mmcblk.p.+|nvme.+|rbd.+|sd.+|vd.+|xvd.+|dm-.+|md.+|dasd.+)",job="kubelet",metrics_path="/metrics/cadvisor",namespace!=""}[1m]
          )
        )
    - record: instance:etcd_disk_wal_fsync_duration_seconds:histogram_quantile99_rate5m
      expr: >-
        histogram_quantile(
          0.99,
          sum by (instance, le) (rate(etcd_disk_wal_fsync_duration_seconds_bucket{job=~".*etcd.*"}[5m]))
        )
    - record: instance:etcd_disk_backend_commit_duration_seconds:histogram_quantile99_rate5m
      expr: >-
        histogram_quantile(
          0.99,
          sum by (instance, le) (rate(etcd_disk_backend_commit_duration_seconds_bucket{job=~".*etcd.*"}[5m]))
        )
