apiVersion: v1
kind: Endpoints
metadata:
  name: prometheus-operator-stork-agent-bind
  labels:
    release: prometheus-operator
    app: prometheus-stork-agent
    app.kubernetes.io/instance: prometheus-operator
    app.kubernetes.io/name: prometheus-operator-stork-agent-bind
  namespace: prometheus-operator
subsets:
- addresses:
  - ip: 10.0.3.10
  - ip: 10.0.3.11
  - ip: 10.0.3.12
  ports:
  - name: metrics
    port: 9119
    protocol: TCP
