apiVersion: v1
kind: Endpoints
metadata:
  name: prometheus-operator-stork-agent-kea
  labels:
    release: prometheus-operator
    app: prometheus-stork-agent
    app.kubernetes.io/instance: prometheus-operator
    app.kubernetes.io/name: prometheus-operator-stork-agent-kea
  namespace: prometheus-operator
subsets:
- addresses:
  - ip: 10.0.3.16
  ports:
  - name: metrics
    port: 9547
    protocol: TCP
