apiVersion: v1
kind: Service
metadata:
  name: prometheus-operator-stork-agent-kea
  labels:
    release: prometheus-operator
    app: prometheus-stork-agent
    app.kubernetes.io/instance: prometheus-operator
    app.kubernetes.io/name: prometheus-operator-stork-agent-kea
  namespace: prometheus-operator
spec:
  clusterIP: None
  ports:
  - name: metrics
    port: 9547
    protocol: TCP
    targetPort: 9547
  type: ClusterIP
