# yaml-language-server: $schema=https://raw.githubusercontent.com/yannh/kubernetes-json-schema/refs/heads/master/master/service-v1.json
apiVersion: v1
kind: Service
metadata:
  name: prometheus-operator-stork-agent-bind
  labels:
    release: prometheus-operator
    app: prometheus-stork-agent
    app.kubernetes.io/instance: prometheus-operator
    app.kubernetes.io/name: prometheus-operator-stork-agent-bind
  namespace: prometheus-operator
spec:
  clusterIP: None
  ports:
  - name: metrics
    port: 9119
    protocol: TCP
    targetPort: 9119
  type: ClusterIP
