# yaml-language-server: $schema=https://raw.githubusercontent.com/datreeio/CRDs-catalog/refs/heads/main/monitoring.coreos.com/servicemonitor_v1.json
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: prometheus-operator-stork-agent-bind
  labels:
    release: prometheus-operator
    app: prometheus-stork-agent
    app.kubernetes.io/instance: prometheus-operator
    app.kubernetes.io/name: prometheus-operator-stork-agent-bind
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: prometheus-operator-stork-agent-bind
  endpoints:
  - port: metrics
  namespaceSelector:
    any: true
