# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ./resources/cert.yaml
- ./resources/service.yaml
- ./resources/httpproxy.yaml
- ./resources/delegation.yaml
- ./resources/statefulset.yaml
- ./resources/serviceaccount.yaml
- ./resources/deployment.yaml
configMapGenerator:
- name: envoy-yaml
  namespace: cert-manager
  options:
    labels:
      app.kubernetes.io/name: plex-media-server
      app.kubernetes.io/instance: plex-media-server
  files:
  - ./files/envoy.yaml
