# yaml-language-server: $schema=https://raw.githubusercontent.com/yannh/kubernetes-json-schema/refs/heads/master/master/service-v1.json
apiVersion: v1
kind: Service
metadata:
  name: plex-media-server
  labels:
    app: plex-media-server
    app.kubernetes.io/name: plex-media-server
    app.kubernetes.io/instance: plex-media-server
  namespace: plex-media-server
spec:
  type: NodePort
  ports:
  - port: 32400
    targetPort: 32400
    nodePort: 32400
    protocol: TCP
    name: pms
  selector:
    app.kubernetes.io/name: plex-media-server
    app.kubernetes.io/instance: plex-media-server
---
# yaml-language-server: $schema=https://raw.githubusercontent.com/yannh/kubernetes-json-schema/refs/heads/master/master/service-v1.json
apiVersion: v1
kind: Service
metadata:
  name: envoy-plex-ingress
  labels:
    app.kubernetes.io/name: envoy-plex
    app.kubernetes.io/instance: plex-media-server
  namespace: cert-manager
spec:
  type: NodePort
  ports:
  - port: 8443
    targetPort: 8443
    nodePort: 31443
    protocol: TCP
    name: https
  selector:
    app.kubernetes.io/name: envoy-plex
    app.kubernetes.io/instance: plex-media-server
