apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: plex-media-server
  labels:
    name: plex-media-server
    app: plex-media-server
    app.kubernetes.io/name: plex-media-server
    app.kubernetes.io/instance: plex-media-server
  namespace: plex-media-server
spec:
  serviceName: plex-media-server
  selector:
    matchLabels:
      app.kubernetes.io/name: plex-media-server
      app.kubernetes.io/instance: plex-media-server
  template:
    metadata:
      labels:
        app: plex-media-server
        app.kubernetes.io/name: plex-media-server
        app.kubernetes.io/instance: plex-media-server
    spec:
      securityContext:
        runAsUser: 65534
        runAsGroup: 65534
        fsGroup: 65534
        fsGroupChangePolicy: OnRootMismatch
      serviceAccountName: plex-media-server
      volumes:
      - name: pms-transcode
        emptyDir: {}
      - name: pms-logs
        emptyDir: {}
      - name: media-movies
        nfs:
          path: /mnt/artemis/data/media/movies
          server: nas1.private.swifthomelab.net
      - name: media-tv
        nfs:
          path: /mnt/artemis/data/media/tv
          server: nas1.private.swifthomelab.net
      - name: movies
        nfs:
          server: nas1.private.swifthomelab.net
          path: /mnt/artemis/data/bt1/completed/movies
      - name: tv
        nfs:
          server: nas1.private.swifthomelab.net
          path: /mnt/artemis/data/bt1/completed/tv
      terminationGracePeriodSeconds: 120
      initContainers: null
      containers:
      - name: plex-media-server-pms
        image: ghcr.io/onedr0p/plex:rolling@sha256:6caeca24f3b08206a94a6a9c102e2c0c14d46d5a9163241716559e8c83f53ff8
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 32400
          name: pms
        env:
        - name: ALLOWED_NETWORKS
          value: 10.0.12.0/24
        - name: HOSTNAME
          value: PlexServer
        - name: PLEX_GID
          value: "1000"
        - name: PLEX_UID
          value: "1000"
        - name: TZ
          value: Etc/UTC
        resources:
          requests:
            cpu: "1.0"
            memory: 3Gi
          limits:
            memory: 4Gi
        volumeMounts:
        - name: pms-config
          mountPath: /config
        - name: pms-transcode
          mountPath: /transcode
        - mountPath: /media/tv
          name: media-tv
        - mountPath: /media/movies
          name: media-movies
        - mountPath: /movies
          name: movies
        - mountPath: /tv
          name: tv
        - mountPath: /config/Library/Application Support/Plex Media Server/Logs
          name: pms-logs
        - mountPath: /config/Library/Application Support/Plex Media Server/Cache
          name: pms-cache
  volumeClaimTemplates:
  - metadata:
      name: pms-config
    spec:
      accessModes: [ReadWriteOnce]
      storageClassName: proxmox-csi
      resources:
        requests:
          storage: 50Gi
  - metadata:
      name: pms-cache
    spec:
      accessModes: [ReadWriteOnce]
      storageClassName: proxmox-csi
      resources:
        requests:
          storage: 25Gi
