apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: vault-swifthomelab-net
  namespace: cert-manager
spec:
  secretName: vault-swifthomelab-net
  issuerRef:
    name: swifthomelab-net-issuer
    kind: ClusterIssuer
  commonName: vault.swifthomelab.net
  dnsNames:
  - vault.swifthomelab.net
