apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: vaultwarden
  labels:
    name: vaultwarden
    app: vaultwarden
    app.kubernetes.io/name: vaultwarden
    app.kubernetes.io/instance: vaultwarden
  namespace: vaultwarden
spec:
  serviceName: vaultwarden
  selector:
    matchLabels:
      app.kubernetes.io/name: vaultwarden
      app.kubernetes.io/instance: vaultwarden
  template:
    metadata:
      labels:
        app: vaultwarden
        app.kubernetes.io/name: vaultwarden
        app.kubernetes.io/instance: vaultwarden
    spec:
      terminationGracePeriodSeconds: 120
      containers:
      - name: vaultwarden
        image: vaultwarden/server:1.32.2-alpine@sha256:7d69bfbf51b74a93e951f9949e7ce772e22ef0161afca8f1403d7144b2bc868d
        imagePullPolicy: IfNotPresent
        env:
        - name: WEBSOCKET_ENABLED
          value: "true"
        ports:
        - containerPort: 80
          name: http
        livenessProbe:
          httpGet:
            path: /alive
            port: 80
        readinessProbe:
          httpGet:
            path: /alive
            port: 80
        volumeMounts:
        - mountPath: /data
          name: vaultwarden
        resources:
          requests:
            cpu: 10m
            memory: 20Mi
          limits:
            cpu: 200m
            memory: 200Mi
  volumeClaimTemplates:
  - metadata:
      name: vaultwarden
    spec:
      accessModes: [ReadWriteOnce]
      storageClassName: csi-rbd-sc
      resources:
        requests:
          storage: 4Gi
