# yaml-language-server: $schema=https://raw.githubusercontent.com/datreeio/CRDs-catalog/refs/heads/main/cert-manager.io/certificate_v1.json
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: jellyfin-swifthomelab-net
  labels:
    app.kubernetes.io/name: jellyfin
    app.kubernetes.io/instance: jellyfin
    app.kubernetes.io/component: media-server
    app.kubernetes.io/part-of: jellyfin
  namespace: cert-manager
spec:
  secretName: jellyfin-swifthomelab-net
  issuerRef:
    name: swifthomelab-net-issuer
    kind: ClusterIssuer
  commonName: jellyfin.swifthomelab.net
  dnsNames:
  - jellyfin.swifthomelab.net
  - music.swifthomelab.net
