apiVersion: projectcontour.io/v1
kind: TLSCertificateDelegation
metadata:
  name: jellyfin-swifthomelab-net
  labels:
    app.kubernetes.io/name: jellyfin
    app.kubernetes.io/instance: jellyfin
    app.kubernetes.io/component: media-server
    app.kubernetes.io/part-of: jellyfin
  namespace: cert-manager
spec:
  delegations:
  - secretName: jellyfin-swifthomelab-net
    targetNamespaces:
    - jellyfin
