apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: jellyfin
  labels:
    app.kubernetes.io/name: jellyfin
    app.kubernetes.io/instance: jellyfin
    app.kubernetes.io/component: media-server
    app.kubernetes.io/part-of: jellyfin
  namespace: jellyfin
spec:
  serviceName: jellyfin
  selector:
    matchLabels:
      app.kubernetes.io/name: jellyfin
      app.kubernetes.io/instance: jellyfin
  template:
    metadata:
      labels:
        app.kubernetes.io/name: jellyfin
        app.kubernetes.io/instance: jellyfin
        app.kubernetes.io/component: media-server
        app.kubernetes.io/part-of: jellyfin
    spec:
      securityContext:
        runAsUser: 65534
        runAsGroup: 65534
        fsGroup: 65534
        fsGroupChangePolicy: OnRootMismatch
      volumes:
      - name: logs
        emptyDir: {}
      - name: tmp
        emptyDir: {}
      - name: music
        nfs:
          path: /mnt/artemis/data/media/music
          server: nas1.private.swifthomelab.net
      terminationGracePeriodSeconds: 90
      containers:
      - name: jellyfin
        image: jellyfin/jellyfin:10.9.11@sha256:efc2f4ebef76f0e8d3ea49c87b4c61c7d8847e496dc1fd5a91ce6652e33c116f
        ports:
        - containerPort: 8096
          name: http
        env:
        - name: JELLYFIN_PublishedServerUrl
          value: https://music.swifthomelab.net
        resources:
          requests:
            cpu: 1500m
            memory: 1000Mi
          limits:
            cpu: 7000m
            memory: 3500Mi
        volumeMounts:
        - name: config
          mountPath: /config
        - name: cache
          mountPath: /cache
        - name: music
          mountPath: /music
        - name: logs
          mountPath: /var/logs
        - name: tmp
          mountPath: /tmp
  volumeClaimTemplates:
  - metadata:
      name: config
    spec:
      accessModes: [ReadWriteOnce]
      storageClassName: csi-rbd-sc
      resources:
        requests:
          storage: 15Gi
  - metadata:
      name: cache
    spec:
      accessModes: [ReadWriteOnce]
      storageClassName: csi-rbd-sc
      resources:
        requests:
          storage: 20Gi
