# yaml-language-server: $schema=https://raw.githubusercontent.com/yannh/kubernetes-json-schema/refs/heads/master/master/statefulset.json
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: jellyfin
  labels:
    app.kubernetes.io/name: jellyfin
    app.kubernetes.io/instance: jellyfin
    app.kubernetes.io/component: media-server
    app.kubernetes.io/part-of: jellyfin
  namespace: jellyfin
spec:
  serviceName: jellyfin
  selector:
    matchLabels:
      app.kubernetes.io/name: jellyfin
      app.kubernetes.io/instance: jellyfin
  template:
    metadata:
      labels:
        app.kubernetes.io/name: jellyfin
        app.kubernetes.io/instance: jellyfin
        app.kubernetes.io/component: media-server
        app.kubernetes.io/part-of: jellyfin
    spec:
      hostAliases:
      - ip: 0.0.0.0
        hostnames:
        - media.theaudiodb.com
        - www.theaudiodb.com
        - theaudiodb.com
        - r2.theaudiodb.com
      securityContext:
        runAsUser: 65534
        runAsGroup: 65534
        fsGroup: 65534
        fsGroupChangePolicy: OnRootMismatch
      volumes:
      - name: logs
        emptyDir: {}
      - name: tmp
        emptyDir: {}
      - name: music
        nfs:
          path: /mnt/artemis/data/media/music
          server: nas1.private.swifthomelab.net
      terminationGracePeriodSeconds: 90
      containers:
      - name: jellyfin
        image: jellyfin/jellyfin:10.10.3@sha256:17c3a8d9dddb97789b5f37112840ebf96566442c14d4754193a6c2eb154bc221
        ports:
        - containerPort: 8096
          name: http
        env:
        - name: JELLYFIN_PublishedServerUrl
          value: https://music.swifthomelab.net
        resources:
          requests:
            cpu: 1500m
            memory: 1000Mi
          limits:
            cpu: 7000m
            memory: 3500Mi
        volumeMounts:
        - name: config
          mountPath: /config
        - name: cache
          mountPath: /cache
        - name: music
          mountPath: /music
        - name: logs
          mountPath: /var/logs
        - name: tmp
          mountPath: /tmp
  volumeClaimTemplates:
  - metadata:
      name: config
    spec:
      accessModes: [ReadWriteOnce]
      storageClassName: csi-rbd-sc
      resources:
        requests:
          storage: 15Gi
  - metadata:
      name: cache
    spec:
      accessModes: [ReadWriteOnce]
      storageClassName: csi-rbd-sc
      resources:
        requests:
          storage: 20Gi
