apiVersion: apps/v1
kind: "StatefulSet"
metadata:
  name: prowlarr
  namespace: prowlarr
  labels:
    app: "prowlarr"
    app.kubernetes.io/name: "prowlarr"
spec:  
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: prowlarr
  persistentVolumeClaimRetentionPolicy:
    whenDeleted: Retain
    whenScaled: Retain
  template:
    metadata:
      labels:
        app: "prowlarr"
        app.kubernetes.io/name: "prowlarr"
    spec:
      serviceAccountName: default
      terminationGracePeriodSeconds: 60
      securityContext:
        runAsUser: 65534
        runAsGroup: 65534
        fsGroup: 65534
        fsGroupChangePolicy: OnRootMismatch
      containers:
        - name: prowlarr
          image: ghcr.io/onedr0p/prowlarr:1.15.0.4361@sha256:cf646c64fdb90f3acddb5e2ec6ffad064392ad1aaf9da7875b8a7a962263f5fc
          ports:
            - name: http
              containerPort: 9696
              protocol: TCP
          volumeMounts:
            - mountPath: /config
              name: prowlarr
          livenessProbe:
            httpGet:
              port: 9696
              path: /
              scheme: HTTP
            initialDelaySeconds: 60
            failureThreshold: 5
            successThreshold: 1
            timeoutSeconds: 10
            periodSeconds: 10
          readinessProbe:
            httpGet:
              port: 9696
              path: /
              scheme: HTTP
            initialDelaySeconds: 10
            failureThreshold: 5
            successThreshold: 2
            timeoutSeconds: 5
            periodSeconds: 10
          startupProbe:
            tcpSocket:
              port: 9696
            initialDelaySeconds: 10
            failureThreshold: 60
            successThreshold: 1
            timeoutSeconds: 2
            periodSeconds: 5
          resources:
            requests:
              cpu: 10m
              memory: 50Mi
            limits: 
              cpu: 1500m 
              memory: 2Gi
          env:
            - name: "UMASK"
              value: "0022"
            - name: "TZ"
              value: "Etc/UTC"
            - name: "PROWLARR__PORT"
              value: "9696"
  volumeClaimTemplates:
    - metadata:
        name: prowlarr
        labels:
          app.kubernetes.io/part-of: "prowlarr"
        namespace: prowlarr
      spec:
        storageClassName: local-storage
        accessModes: [ "ReadWriteOncePod" ]
        resources:
          requests:
            storage: 8Gi
