# yaml-language-server: $schema=https://raw.githubusercontent.com/yannh/kubernetes-json-schema/refs/heads/master/master/statefulset.json
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: ntfy
  labels:
    app.kubernetes.io/name: ntfy
    app.kubernetes.io/instance: ntfy
    app.kubernetes.io/component: server
    app.kubernetes.io/part-of: ntfy
  namespace: ntfy
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: ntfy
      app.kubernetes.io/instance: ntfy
  serviceName: ntfy
  template:
    metadata:
      labels:
        app.kubernetes.io/name: ntfy
        app.kubernetes.io/instance: ntfy
        app.kubernetes.io/component: server
        app.kubernetes.io/part-of: ntfy
    spec:
      securityContext:
        runAsUser: 65534
        fsGroupChangePolicy: OnRootMismatch
        runAsGroup: 65534
        runAsNonRoot: true
        fsGroup: 65534
        seccompProfile:
          type: RuntimeDefault
        sysctls:
        - name: net.ipv4.ip_unprivileged_port_start
          value: "80"
      hostIPC: false
      hostNetwork: false
      hostPID: false
      volumes:
      - name: config
        configMap:
          name: ntfy
      terminationGracePeriodSeconds: 90
      containers:
      - name: ntfy
        image: binwiederhier/ntfy:v2.11.0@sha256:38ef0bd584de2a11414c9b7330c03e5a542a312fd5078e09fc4a99e4cdd43352
        args: [serve, --cache-file, /var/cache/ntfy/cache.db]
        ports:
        - containerPort: 80
          name: http
        volumeMounts:
        - name: config
          mountPath: /etc/ntfy
          readOnly: true
        - name: cache
          mountPath: /var/cache/ntfy
        livenessProbe:
          failureThreshold: 5
          httpGet:
            path: /v1/health
            port: 80
          initialDelaySeconds: 2
          periodSeconds: 10
          timeoutSeconds: 1
        readinessProbe:
          failureThreshold: 3
          httpGet:
            path: /v1/health
            port: 80
          initialDelaySeconds: 8
          periodSeconds: 10
          timeoutSeconds: 1
  volumeClaimTemplates:
  - metadata:
      name: cache
    spec:
      accessModes: [ReadWriteOnce]
      storageClassName: csi-rbd-sc
      resources:
        requests:
          storage: 1Gi
