gitea:
  strategy:
    type: Recreate
  gitea:
    metrics:
      enabled: true
      serviceMonitor:
        enabled: true
    config:
      server:
        HTTP_PORT: 3000
  postgresql:
    enabled: false
  postgresql-ha:
    enabled: false
  valkey:
    enabled: false
  valkey-cluster:
    enabled: false
  service:
    http:
      port: 3000
    ssh:
      type: NodePort
      port: 22
      nodePort: 30022
