gitea:
  namespace: gitea
  replicaCount: 1
  image:
    rootless: true
    fullOverride: docker.io/gitea/gitea:latest-rootless@sha256:be0b89adf2fc8657df508303d919c3be33e6413605882919f702177d62960c9a
  strategy:
    type: Recreate
  gitea:
    admin:
      existingSecret: gitea-admin-secret
    additionalConfigSources:
    - secret:
        secretName: gitea-app-ini-secret
    - configMap:
        name: gitea-app-ini
    metrics:
      enabled: true
      serviceMonitor:
        enabled: true
    config:
      server:
        HTTP_PORT: 3000
        SSH_LISTEN_PORT: 2222
  extraVolumes:
  - name: robots-txt
    configMap:
      name: robots-txt
  extraContainerVolumeMounts:
  - name: robots-txt
    mountPath: /data/gitea/robots-txt
  postgresql:
    enabled: false
  postgresql-ha:
    enabled: false
  valkey:
    enabled: false
  valkey-cluster:
    enabled: false
  service:
    http:
      port: 3000
    ssh:
      type: NodePort
      port: 22          # service
      targetPort: 2222  # container
      nodePort: 30022   # external
  podSecurityContext:
    fsGroup: 65534
  containerSecurityContext:
    allowPrivilegeEscalation: false
    capabilities:
      drop:
      - ALL
      add:
      - SYS_CHROOT  # issues/161
    privileged: false
    readOnlyRootFilesystem: true
    runAsGroup: 65534
    runAsUser: 65534
    runAsNonRoot: true
  persistence:
    claimName: gitea-shared-storage
    storageClass: csi-rbd-sc
  # # Configure commit/action signing prerequisites
  # ## @section Signing
  # #
  # ## @param signing.enabled Enable commit/action signing
  # ## @param signing.gpgHome GPG home directory
  # ## @param signing.privateKey Inline private gpg key for signed internal Git activity
  # ## @param signing.existingSecret Use an existing secret to store the value of `signing.privateKey`
  # signing:
  #   enabled: false
  #   gpgHome: /data/git/.gnupg
  #   privateKey: ""
  #   existingSecret: ""
