gitea:
  gitea:
    config:
      server:
        HTTP_PORT: 3000
  postgresql:
    enabled: false
  postgresql-ha:
    enabled: false
  valkey:
    enabled: false
  valkey-cluster:
    enabled: false
  service:
    http:
      port: 3000
    ssh:
      port: 22
