gitea:
  image:
    fullOverride: docker.io/gitea/gitea:1.23.8-rootless@sha256:331875f35bdcc3c1110fc8410a4e809e3103ebb091ef424fec2df53ac1b658fc
  strategy:
    type: Recreate
  gitea:
    metrics:
      enabled: true
      serviceMonitor:
        enabled: true
    config:
      server:
        HTTP_PORT: 3000
  postgresql:
    enabled: false
  postgresql-ha:
    enabled: false
  valkey:
    enabled: false
  valkey-cluster:
    enabled: false
  service:
    http:
      port: 3000
    ssh:
      type: NodePort
      port: 22
      nodePort: 30022
