# yaml-language-server: $schema=https://raw.githubusercontent.com/datreeio/CRDs-catalog/refs/heads/main/projectcontour.io/httpproxy_v1.json
apiVersion: projectcontour.io/v1
kind: HTTPProxy
metadata:
  name: memos-ingress
  namespace: memos
spec:
  virtualhost:
    fqdn: memos.swifthomelab.net
    tls:
      secretName: cert-manager/memos-swifthomelab-net
  routes:
  - services:
    - name: memos
      port: 5230
    conditions:
    - prefix: /
    timeoutPolicy:
      response: 60s  # if NULL, uses 15s (envoy default)
  - services:
    - name: memos
      port: 5230
    conditions:
    - prefix: /api/v1/sse
    - header:
        name: Accept
        contains: text/event-stream
    timeoutPolicy:
      # sse must emit keepalive events else this needs to be set to infinity as well
      idle: 600s
      idleConnection: 600s
      # The following is required as-is for SSE to work properly:
      #   * a value of either null or 0s will revert to the default 15s timeout
      #   * route timeouts must be disabled for streaming responses or they will
      #     always be closed after timeout regardless of keepalive
      # See note on official docs: https://www.envoyproxy.io/docs/envoy/v1.37.0/faq/configuration/timeouts#route-timeouts
      response: infinity
