apiVersion: v1
kind: Service
metadata:
  labels:
    name: flaresolverr
    app: flaresolverr
    app.kubernetes.io/name: flaresolverr
    app.kubernetes.io/instance: flaresolverr
  name: flaresolverr
  namespace: flaresolverr
spec:
  ports:
    - name: http
      targetPort: 8080
      protocol: TCP
      port: 8080
    - name: metrics
      targetPort: 8181
      protocol: TCP
      port: 8181
  selector:
    app: flaresolverr
