apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: radarr-swifthomelab-net
  namespace: cert-manager
spec:
  secretName: radarr-swifthomelab-net
  issuerRef:
    name: swifthomelab-net-issuer
    kind: ClusterIssuer
  commonName: radarr.swifthomelab.net
  dnsNames:
  - radarr.swifthomelab.net
