apiVersion: projectcontour.io/v1
kind: TLSCertificateDelegation
metadata:
  name: radarr-swifthomelab-net
  namespace: cert-manager
spec:
  delegations:
  - secretName: radarr-swifthomelab-net
    targetNamespaces:
    - radarr
