# yaml-language-server: $schema=https://raw.githubusercontent.com/yannh/kubernetes-json-schema/refs/heads/master/master/statefulset.json
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: radarr
  namespace: radarr
  labels:
    app: radarr
    app.kubernetes.io/name: radarr
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: radarr
  serviceName: radarr
  persistentVolumeClaimRetentionPolicy:
    whenDeleted: Retain
    whenScaled: Retain
  revisionHistoryLimit: 3
  template:
    metadata:
      labels:
        app: radarr
        app.kubernetes.io/name: radarr
    spec:
      serviceAccountName: default
      terminationGracePeriodSeconds: 60
      securityContext:
        runAsUser: 65534
        runAsGroup: 65534
        fsGroup: 65534
        fsGroupChangePolicy: OnRootMismatch
      volumes:
      - name: media
        nfs:
          path: /mnt/artemis/data/media
          server: nas1.private.swifthomelab.net
      containers:
      - name: radarr
        image: ghcr.io/home-operations/radarr:5.27.3.10153@sha256:1bf822eaf3d944dc994656c3a712a89df0d88f5f46731af4fccc90c5e0333167
        ports:
        - name: http
          containerPort: 7878
          protocol: TCP
        volumeMounts:
        - mountPath: /config
          name: radarr
        - mountPath: /mnt/media
          name: media
        livenessProbe:
          httpGet:
            port: 7878
            path: /
            scheme: HTTP
          initialDelaySeconds: 60
          failureThreshold: 5
          successThreshold: 1
          timeoutSeconds: 10
          periodSeconds: 10
        readinessProbe:
          httpGet:
            port: 7878
            path: /
            scheme: HTTP
          initialDelaySeconds: 10
          failureThreshold: 5
          successThreshold: 2
          timeoutSeconds: 5
          periodSeconds: 10
        startupProbe:
          tcpSocket:
            port: 7878
          initialDelaySeconds: 10
          failureThreshold: 60
          successThreshold: 1
          timeoutSeconds: 2
          periodSeconds: 5
        resources:
          requests:
            cpu: 10m
            memory: 50Mi
          limits:
            cpu: 500m
            memory: 500Mi
        env:
        - name: UMASK
          value: "0022"
        - name: TZ
          value: Etc/UTC
        - name: RADARR__PORT
          value: "7878"
  volumeClaimTemplates:
  - metadata:
      name: radarr
      labels:
        app.kubernetes.io/part-of: radarr
      namespace: radarr
    spec:
      storageClassName: csi-rbd-sc
      accessModes: [ReadWriteOncePod]
      resources:
        requests:
          storage: 8Gi
