# yaml-language-server: $schema=https://raw.githubusercontent.com/datreeio/CRDs-catalog/refs/heads/main/projectcontour.io/httpproxy_v1.json
apiVersion: projectcontour.io/v1
kind: HTTPProxy
metadata:
  name: rustfs-ingress
  namespace: rustfs
spec:
  virtualhost:
    fqdn: s3.swifthomelab.net
    tls:
      secretName: cert-manager/s3-swifthomelab-net
  routes:
  - conditions:
    - prefix: /
    services:
    - name: rustfs-svc
      port: 9000
    timeoutPolicy:
      response: 60s  # if NULL, uses 15s (envoy default)
