# ---
# apiVersion: cert-manager.io/v1
# kind: Certificate
# metadata:
#   name: k8s-private-swifthomelab-net-production
#   namespace: cert-manager
#   annotations:
#     argocd.argoproj.io/sync-wave: "1"
# spec:
#   secretName: k8s-private-swifthomelab-net-production
#   issuerRef:
#     name: letsencrypt-production
#     kind: ClusterIssuer
#   commonName: "*.k8s.private.swifthomelab.net"
#   dnsNames:
#   - "k8s.private.swifthomelab.net"
#   - "*.k8s.private.swifthomelab.net"
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: k8s-private-swifthomelab-net-staging
  namespace: cert-manager
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  secretName: k8s-private-swifthomelab-net-staging
  issuerRef:
    name: letsencrypt-staging
    kind: ClusterIssuer
  commonName: "*.k8s.private.swifthomelab.net"
  dnsNames:
  - "k8s.private.swifthomelab.net"
  - "*.k8s.private.swifthomelab.net"
