# ---
# apiVersion: cert-manager.io/v1
# kind: ClusterIssuer
# metadata:
#   name: letsencrypt-production
#   namespace: cert-manager
#   annotations:
#     argocd.argoproj.io/sync-wave: "1"
# spec:
#   acme:
#     server: https://acme-v02.api.letsencrypt.org/directory
#     email: 85815005+JosBritton@users.noreply.github.com
#     privateKeySecretRef:
#       name: letsencrypt-production
#     solvers:
#       - dns01:
#           cloudflare:
#             email: 85815005+JosBritton@users.noreply.github.com
#             apiTokenSecretRef:
#               name: cloudflare-token-secret
#               key: cloudflare-token
#         selector:
#           dnsZones:
#             - "swifthomelab.net"
---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-staging
  namespace: cert-manager
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  acme:
    server: https://acme-staging-v02.api.letsencrypt.org/directory
    email: 85815005+JosBritton@users.noreply.github.com
    privateKeySecretRef:
      name: letsencrypt-staging
    solvers:
      - dns01:
          cloudflare:
            email: 85815005+JosBritton@users.noreply.github.com
            apiTokenSecretRef:
              name: cloudflare-token-secret
              key: cloudflare-token
        selector:
          dnsZones:
            - "swifthomelab.net"
