apiVersion: "apps/v1"
kind: "Deployment"
metadata:
  labels:
    app: "vaultwarden"
  name: "vaultwarden"
  namespace: "vaultwarden"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: "vaultwarden"
  strategy:
    type: "Recreate"
  template:
    metadata:
      labels:
        app: "vaultwarden"
    spec:
      containers:
        - env:
            - name: "WEBSOCKET_ENABLED"
              value: "true"
          image: "vaultwarden/server:1.30.5-alpine"
          name: "vaultwarden"
          ports:
            - containerPort: 80
          volumeMounts:
            - mountPath: "/data"
              name: "vaultwarden"
          livenessProbe:
            httpGet:
              path: "/alive"
              port: 80
          readinessProbe:
            httpGet:
              path: "/alive"
              port: 80
      restartPolicy: "Always"
      volumes:
        - name: "vaultwarden"
          persistentVolumeClaim:
            claimName: "vaultwarden"
