apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: vaultwarden
  labels:
    name: vaultwarden
    app: vaultwarden
    app.kubernetes.io/name: vaultwarden
    app.kubernetes.io/instance: vaultwarden
  namespace: vaultwarden
spec:
  serviceName: vaultwarden
  selector:
    matchLabels:
      app.kubernetes.io/name: vaultwarden
      app.kubernetes.io/instance: vaultwarden
  template:
    metadata:
      labels:
        app: vaultwarden
        app.kubernetes.io/name: vaultwarden
        app.kubernetes.io/instance: vaultwarden
    spec:
      terminationGracePeriodSeconds: 120
      containers:
        - name: "vaultwarden"
          image: "vaultwarden/server:1.30.5-alpine"
          imagePullPolicy: IfNotPresent
          env:
            - name: "WEBSOCKET_ENABLED"
              value: "true"
          ports:
            - containerPort: 80
              name: http
          livenessProbe:
            httpGet:
              path: "/alive"
              port: 80
          readinessProbe:
            httpGet:
              path: "/alive"
              port: 80
          volumeMounts:
            - mountPath: "/data"
              name: "vaultwarden"
  volumeClaimTemplates:
    - metadata:
        name: vaultwarden
      spec:
        accessModes: [ ReadWriteOnce ]
        storageClassName: proxmox-csi
        resources:
          requests:
            storage: 4Gi
