# yaml-language-server: $schema=https://raw.githubusercontent.com/yannh/kubernetes-json-schema/refs/heads/master/master/service-v1.json
apiVersion: v1
kind: Service
metadata:
  name: webdav
  namespace: webdav
  labels:
    app.kubernetes.io/name: webdav
    app.kubernetes.io/instance: webdav
spec:
  type: ClusterIP
  ports:
  - name: http
    port: 80
    targetPort: http
    protocol: TCP
  selector:
    app.kubernetes.io/name: webdav
    app.kubernetes.io/instance: webdav
