apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: valkey
  labels:
    app.kubernetes.io/name: valkey
    app.kubernetes.io/instance: valkey
    app.kubernetes.io/managed-by: Helm
spec:
  template:
    spec:
      initContainers:
      - name: valkey-init
        image: docker.io/valkey/valkey:9.1.0@sha256:4963247afc4cd33c7d3b2d2816b9f7f8eeebab148d29056c2ca4d7cbc966f2d9
      containers:
      - name: valkey
        image: docker.io/valkey/valkey:9.1.0@sha256:4963247afc4cd33c7d3b2d2816b9f7f8eeebab148d29056c2ca4d7cbc966f2d9
      - name: metrics
        image: ghcr.io/oliver006/redis_exporter:v1.79.0@sha256:67e175f144212fe5796b3134dae1f3db33782b57dc53f7c6f5d938f8f70d9754
---
apiVersion: v1
kind: Pod
metadata:
  name: valkey-test-auth-existing
  labels:
    app.kubernetes.io/name: valkey
    app.kubernetes.io/instance: valkey
    app.kubernetes.io/managed-by: Helm
spec:
  containers:
  - name: test-auth
    image: docker.io/valkey/valkey:9.1.0@sha256:4963247afc4cd33c7d3b2d2816b9f7f8eeebab148d29056c2ca4d7cbc966f2d9
