apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./resources/upstream.yaml
  - ./resources/argocd-metrics-servicemonitor.yaml
  - ./resources/argocd-server-metrics-servicemonitor.yaml
  - ./resources/argocd-repo-server-metrics-servicemonitor.yaml
  - ./resources/argocd-notifications-controller-metrics-servicemonitor.yaml
  - ./resources/cert.yaml
  - ./resources/httpproxy.yaml
  - ./resources/delegation.yaml
# generatorOptions:
#   disableNameSuffixHash: true
#   labels:
#     grafana_dashboard: argocd
# configMapGenerator:
#   - files:
#     - dashboard.json
#     name: argocd-dashboard-cm
patches:
  - path: overlays/prometheus-operator-grafana-secret.yaml
    target:
      kind: Secret
      name: prometheus-operator-grafana
      namespace: prometheus-operator
      version: v1
  - path: overlays/prometheus-crds-annotations.yaml
    target:
      group: apiextensions.k8s.io
      kind: CustomResourceDefinition
      name: .*
      version: v1
  # - path: overlays/prometheus-operator-grafana-cm.yaml
