# yaml-language-server: $schema=https://raw.githubusercontent.com/yannh/kubernetes-json-schema/refs/heads/master/master/cronjob.json
apiVersion: batch/v1
kind: CronJob
metadata:
  name: ddns
  namespace: ddns
spec:
  schedule: "*/5 * * * *"  # every 5 minutes
  jobTemplate:
    spec:
      template:
        spec:
          restartPolicy: OnFailure
          securityContext:
            fsGroup: 65534
            fsGroupChangePolicy: OnRootMismatch
            runAsNonRoot: true
            seccompProfile:
              type: RuntimeDefault
          # periodically restart/reschedule tdarr server
          containers:
          - name: ddns
            image: git.swifthomelab.net/josbritton/ddns:latest@sha256:84cc801b81c0d78272ff015cb00821030c0c613e388822df79d3942dd9c791da
            env:
            - name: APIKEY
              valueFrom:
                secretKeyRef:
                  name: cfcreds
                  key: apikey
            - name: ZONE
              valueFrom:
                secretKeyRef:
                  name: cfcreds
                  key: zoneid
            - name: SUBDOMAIN
              value: dyn
            securityContext:
              allowPrivilegeEscalation: false
              readOnlyRootFilesystem: true
              runAsUser: 65534
              runAsGroup: 65534
              capabilities:
                drop: [ALL]
            resources:
              requests:
                cpu: 10m
                memory: 32Mi
