apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: prowlarr-swifthomelab-net
  namespace: cert-manager
spec:
  secretName: prowlarr-swifthomelab-net
  issuerRef:
    name: swifthomelab-net-issuer
    kind: ClusterIssuer
  commonName: prowlarr.swifthomelab.net
  dnsNames:
  - prowlarr.swifthomelab.net
