apiVersion: projectcontour.io/v1
kind: TLSCertificateDelegation
metadata:
  name: prowlarr-swifthomelab-net
  namespace: cert-manager
spec:
  delegations:
  - secretName: prowlarr-swifthomelab-net
    targetNamespaces:
    - prowlarr
