# yaml-language-server: $schema=https://raw.githubusercontent.com/datreeio/CRDs-catalog/refs/heads/main/projectcontour.io/httpproxy_v1.json
apiVersion: projectcontour.io/v1
kind: HTTPProxy
metadata:
  name: prowlarr-ingress
  namespace: prowlarr
spec:
  virtualhost:
    fqdn: prowlarr.swifthomelab.net
    tls:
      secretName: cert-manager/prowlarr-swifthomelab-net
  routes:
  - services:
    - name: prowlarr
      port: 9696
