apiVersion: v1
kind: Service
metadata:
  name: prowlarr
  namespace: prowlarr
  labels:
    app: "prowlarr"
    app.kubernetes.io/name: "prowlarr"
spec:
  type: ClusterIP
  publishNotReadyAddresses: false
  ports:
    - name: http
      port: 9696
      protocol: TCP
      targetPort: 9696
  selector:
    app.kubernetes.io/name: prowlarr
