apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: prowlarr
  namespace: prowlarr
  labels:
    app: prowlarr
    app.kubernetes.io/name: prowlarr
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: prowlarr
  serviceName: prowlarr
  persistentVolumeClaimRetentionPolicy:
    whenDeleted: Retain
    whenScaled: Retain
  template:
    metadata:
      labels:
        app: prowlarr
        app.kubernetes.io/name: prowlarr
    spec:
      serviceAccountName: default
      terminationGracePeriodSeconds: 60
      securityContext:
        runAsUser: 65534
        runAsGroup: 65534
        fsGroup: 65534
        fsGroupChangePolicy: OnRootMismatch
      containers:
      - name: prowlarr
        image: ghcr.io/onedr0p/prowlarr:1.24.3.4754@sha256:60792494427fcb4bec8337fb76052bec084ede7fc91d40c304641b4c3b1f0781
        ports:
        - name: http
          containerPort: 9696
          protocol: TCP
        volumeMounts:
        - mountPath: /config
          name: prowlarr
        livenessProbe:
          httpGet:
            port: 9696
            path: /
            scheme: HTTP
          initialDelaySeconds: 60
          failureThreshold: 5
          successThreshold: 1
          timeoutSeconds: 10
          periodSeconds: 10
        readinessProbe:
          httpGet:
            port: 9696
            path: /
            scheme: HTTP
          initialDelaySeconds: 10
          failureThreshold: 5
          successThreshold: 2
          timeoutSeconds: 5
          periodSeconds: 10
        startupProbe:
          tcpSocket:
            port: 9696
          initialDelaySeconds: 10
          failureThreshold: 60
          successThreshold: 1
          timeoutSeconds: 2
          periodSeconds: 5
        resources:
          requests:
            cpu: 150m
            memory: 50Mi
          limits:
            cpu: 500m
            memory: 512Mi
        env:
        - name: UMASK
          value: "0022"
        - name: TZ
          value: Etc/UTC
        - name: PROWLARR__PORT
          value: "9696"
  volumeClaimTemplates:
  - metadata:
      name: prowlarr
      labels:
        app.kubernetes.io/part-of: prowlarr
      namespace: prowlarr
    spec:
      storageClassName: csi-rbd-sc
      accessModes: [ReadWriteOncePod]
      resources:
        requests:
          storage: 8Gi
