apiVersion: v1
kind: PersistentVolume
metadata:
  name: radarr
  labels:
    app.kubernetes.io/part-of: "radarr"
  namespace: radarr 
spec:
  capacity:
    storage: 8Gi
  volumeMode: Filesystem
  accessModes: [ "ReadWriteOncePod" ]
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-storage
  local:
    path: /var/lib/radarr
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
            - k8s3.private.swifthomelab.net
