# yaml-language-server: $schema=https://raw.githubusercontent.com/yannh/kubernetes-json-schema/refs/heads/master/master/deployment.json
apiVersion: apps/v1
kind: Deployment
metadata:
  name: wikimore
  labels:
    app.kubernetes.io/name: wikimore
    app.kubernetes.io/instance: wikimore
    app.kubernetes.io/component: frontend
    app.kubernetes.io/part-of: web-mirror
  namespace: web-mirror
spec:
  revisionHistoryLimit: 3
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: wikimore
      app.kubernetes.io/instance: wikimore
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app.kubernetes.io/name: wikimore
        app.kubernetes.io/instance: wikimore
        app.kubernetes.io/component: frontend
        app.kubernetes.io/part-of: web-mirror
    spec:
      containers:
      - name: wikimore
        image: git.private.coffee/privatecoffee/wikimore:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8109
          protocol: TCP
          name: http
        resources:
          limits:
            cpu: 500m
            memory: 300Mi
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - ALL
          readOnlyRootFilesystem: true
      terminationGracePeriodSeconds: 30
      enableServiceLinks: false
      serviceAccountName: default
      automountServiceAccountToken: true
      securityContext:
        fsGroup: 65534
        fsGroupChangePolicy: OnRootMismatch
        runAsGroup: 65534
        runAsNonRoot: true
        runAsUser: 65534
        seccompProfile:
          type: RuntimeDefault
      hostIPC: false
      hostNetwork: false
      hostPID: false
      restartPolicy: Always
