# yaml-language-server: $schema=https://raw.githubusercontent.com/yannh/kubernetes-json-schema/refs/heads/master/master/cronjob.json
apiVersion: batch/v1
kind: CronJob
metadata:
  name: tdarr-nanny
  namespace: tdarr
spec:
  schedule: 0 */6 * * *  # every 6 hours: 0, 6, 12, 18
  suspend: false
  jobTemplate:
    spec:
      template:
        spec:
          serviceAccountName: tdarr-nanny-sa
          restartPolicy: OnFailure
          securityContext:
            fsGroup: 65534
            fsGroupChangePolicy: OnRootMismatch
            runAsNonRoot: true
            seccompProfile:
              type: RuntimeDefault
          # periodically restart/reschedule tdarr server
          containers:
          - name: kubectl
            image: registry.k8s.io/kubectl:v1.35.3@sha256:8dad99b604a2c0bafe17f53cadf78482d6f667a6da687f385508f5f4e4696d37
            command:
            - kubectl rollout -n tdarr restart statefulset tdarr
            securityContext:
              allowPrivilegeEscalation: false
              readOnlyRootFilesystem: true
              runAsUser: 65534
              runAsGroup: 65534
              capabilities:
                drop: [ALL]
            resources:
              requests:
                cpu: 10m
                memory: 32Mi
