# yaml-language-server: $schema=https://raw.githubusercontent.com/yannh/kubernetes-json-schema/refs/heads/master/master/cronjob.json
apiVersion: batch/v1
kind: CronJob
metadata:
  name: tdarr-nanny
  namespace: tdarr
spec:
  schedule: 0 */6 * * *  # every 6 hours: 0, 6, 12, 18
  jobTemplate:
    spec:
      template:
        spec:
          serviceAccountName: tdarr-nanny-sa
          restartPolicy: OnFailure
          securityContext:
            fsGroup: 65534
            fsGroupChangePolicy: OnRootMismatch
            runAsNonRoot: true
            seccompProfile:
              type: RuntimeDefault
          # periodically restart/reschedule tdarr server
          containers:
          - name: kubectl
            image: bitnami/kubectl:1.33.4@sha256:ed0b31a0508da84ee655c5c6e01bd3897fc56ad6cf69debb27fa1893a06d2246
            command:
            - /bin/sh
            - -c
            - kubectl -n tdarr rollout restart statefulset tdarr
            securityContext:
              allowPrivilegeEscalation: false
              readOnlyRootFilesystem: true
              runAsUser: 65534
              runAsGroup: 65534
              capabilities:
                drop: [ALL]
            resources:
              requests:
                cpu: 10m
                memory: 32Mi
