apiVersion: apps/v1
kind: DaemonSet
metadata:
  labels:
    app: tdarr-node
  name: tdarr-node
spec:
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: tdarr-node
  template:
    metadata:
      labels:
        app: tdarr-node
    spec:
      containers:
      - env:
        - name: S6_READ_ONLY_ROOT
          value: "1"
        - name: UMASK
          value: "0022"
        - name: TZ
          value: Etc/UTC
        - name: PUID
          value: "65534"
        - name: PGID
          value: "65534"
        - name: serverIP
          value: tdarr.tdarr.svc.cluster.local
        - name: serverPort
          value: "8266"
        image: ghcr.io/haveagitgat/tdarr_node:2.24.03@sha256:16ab63cf2344bb673e743fd21b363bbdf0adf94fe2d6ed6a4d9dfc6b0139785e
        imagePullPolicy: IfNotPresent
        name: tdarr-node
        ports:
        - containerPort: 8266
          protocol: TCP
        volumeMounts:
        - mountPath: /media
          name: media
      volumes:
      - name: media
        nfs:
          path: /mnt/artemis/data/media
          server: nas1.private.swifthomelab.net
