apiVersion: apps/v1
kind: DaemonSet
metadata:
  labels:
    app: tdarr-node
  name: tdarr-node
spec:
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: tdarr-node
  template:
    metadata:
      labels:
        app: tdarr-node
    spec:
      containers:
      - env:
        - name: S6_READ_ONLY_ROOT
          value: "1"
        - name: UMASK
          value: "0022"
        - name: TZ
          value: Etc/UTC
        - name: PUID
          value: "65534"
        - name: PGID
          value: "65534"
        - name: serverIP
          value: tdarr.tdarr.svc.cluster.local
        - name: serverPort
          value: "8266"
        image: ghcr.io/haveagitgat/tdarr_node:2.25.01@sha256:7b0d6d4160c0aaa5fe007a3adf4017f742aa52cd89f1bb2c79620b41ef39196d
        imagePullPolicy: IfNotPresent
        name: tdarr-node
        ports:
        - containerPort: 8266
          protocol: TCP
        volumeMounts:
        - mountPath: /mnt/media
          name: media
      volumes:
      - name: media
        nfs:
          path: /mnt/artemis/data/media
          server: nas1.private.swifthomelab.net
