# yaml-language-server: $schema=https://raw.githubusercontent.com/yannh/kubernetes-json-schema/refs/heads/master/master/daemonset.json
apiVersion: apps/v1
kind: DaemonSet
metadata:
  labels:
    app: tdarr-node
  name: tdarr-node
  namespace: tdarr
spec:
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: tdarr-node
  template:
    metadata:
      labels:
        app: tdarr-node
    spec:
      # do not schedule on nodes where tdarr server is running
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: tdarr-sa-host
                operator: NotIn
                values: ["true"]
      containers:
      - env:
        - name: S6_READ_ONLY_ROOT
          value: "1"
        - name: UMASK
          value: "0022"
        - name: TZ
          value: Etc/UTC
        - name: PUID
          value: "65534"
        - name: PGID
          value: "65534"
        - name: serverIP
          value: tdarr-server.tdarr.svc.cluster.local
        - name: serverPort
          value: "8266"
        image: ghcr.io/haveagitgat/tdarr_node:2.45.01@sha256:b343008636910a2c1d5c0768e979d6c2e184baf26c642ce3c2405cedf38db466
        imagePullPolicy: IfNotPresent
        name: tdarr-node
        command: [sh, -c, ln -s /usr/local/bin/ffmpeg /usr/bin/ffmpeg && exec /init]
        ports:
        - containerPort: 8266
          protocol: TCP
        volumeMounts:
        - mountPath: /mnt/media
          name: media
        resources:
          requests:
            cpu: 2m
            memory: 450Mi
          limits:
            # high throttling for fairness
            cpu: 1.3
            memory: 4Gi
      volumes:
      - name: media
        nfs:
          path: /mnt/artemis/data/media
          server: nas1.private.swifthomelab.net
