# yaml-language-server: $schema=https://raw.githubusercontent.com/datreeio/CRDs-catalog/refs/heads/main/projectcontour.io/httpproxy_v1.json
apiVersion: projectcontour.io/v1
kind: HTTPProxy
metadata:
  name: tdarr-ingress
  namespace: tdarr
spec:
  virtualhost:
    fqdn: tdarr.swifthomelab.net
    tls:
      secretName: cert-manager/tdarr-swifthomelab-net
  routes:
  - services:
    - name: tdarr
      port: 8265
