---
# yaml-language-server: $schema=https://raw.githubusercontent.com/yannh/kubernetes-json-schema/refs/heads/master/master/serviceaccount.json
apiVersion: v1
kind: ServiceAccount
metadata:
  name: tdarr-nanny-sa
  namespace: tdarr
---
# yaml-language-server: $schema=https://raw.githubusercontent.com/yannh/kubernetes-json-schema/refs/heads/master/master/role.json
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: tdarr-nanny-role
  namespace: tdarr
rules:
- verbs: [get, patch]
  resources: [statefulsets]
  apiGroups: [apps]
---
# yaml-language-server: $schema=https://raw.githubusercontent.com/yannh/kubernetes-json-schema/refs/heads/master/master/rolebinding.json
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: tdarr-nanny-rb
  namespace: tdarr
subjects:
- kind: ServiceAccount
  name: tdarr-nanny-sa
  namespace: tdarr
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: tdarr-nanny-role
