# yaml-language-server: $schema=https://raw.githubusercontent.com/yannh/kubernetes-json-schema/refs/heads/master/master/statefulset.json
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: tdarr
  labels:
    name: tdarr
    app: tdarr
    app.kubernetes.io/name: tdarr
    app.kubernetes.io/instance: tdarr
  namespace: tdarr
spec:
  selector:
    matchLabels:
      app: tdarr
  serviceName: tdarr
  replicas: 1
  persistentVolumeClaimRetentionPolicy:
    whenDeleted: Retain
    whenScaled: Retain
  revisionHistoryLimit: 3
  template:
    metadata:
      labels:
        app: tdarr
    spec:
      serviceAccountName: tdarr-node-labeler-sa
      initContainers:
      - name: tdarr-node-labeler
        image: bitnami/kubectl:1.33.4@sha256:ed0b31a0508da84ee655c5c6e01bd3897fc56ad6cf69debb27fa1893a06d2246
        command:
        - /bin/sh
        - -c
        - |
          kubectl label nodes -l "kubernetes.io/hostname!=$NODE" tdarr-sa-host="false" --overwrite && \
          kubectl label node "$NODE" tdarr-sa-host="true" --overwrite
        env:
        - name: NODE
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        securityContext:
          allowPrivilegeEscalation: false
          readOnlyRootFilesystem: true
          runAsUser: 65534
          runAsGroup: 65534
          capabilities:
            drop: [ALL]
        resources:
          requests:
            cpu: 10m
            memory: 32Mi
      containers:
      - name: tdarr
        image: ghcr.io/haveagitgat/tdarr:2.45.01@sha256:69d28aff66318ecc1c9496717c1731fbdbbfb8c0c4664a90bbb36747fbf279fe
        imagePullPolicy: IfNotPresent
        env:
        - name: S6_READ_ONLY_ROOT
          value: "1"
        - name: UMASK
          value: "0022"
        - name: TZ
          value: Etc/UTC
        - name: PUID
          value: "65534"
        - name: PGID
          value: "65534"
        - name: internalNode
          value: "false"
        - name: nodeID
          value: internal
        ports:
        - containerPort: 8265
          name: ui
        - containerPort: 8266
          name: server
        livenessProbe:
          httpGet:
            path: /api/v2/status
            port: 8266
            scheme: HTTP
          initialDelaySeconds: 60
          failureThreshold: 5
          successThreshold: 1
          timeoutSeconds: 10
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /api/v2/status
            port: 8266
            scheme: HTTP
          initialDelaySeconds: 10
          failureThreshold: 5
          successThreshold: 2
          timeoutSeconds: 5
          periodSeconds: 10
        startupProbe:
          tcpSocket:
            port: 8266
          initialDelaySeconds: 10
          failureThreshold: 60
          successThreshold: 1
          timeoutSeconds: 2
          periodSeconds: 5
        volumeMounts:
        - mountPath: /app/configs
          name: config
        - mountPath: /app/server
          name: server
        - mountPath: /app/logs
          name: logs
        - mountPath: /mnt/media
          name: media
        # extreme disk thrashing from temp database operations
        # this CANNOT EVER be put on storage again
        - mountPath: /var/tmp
          name: var-tmp
        resources:
          requests:
            cpu: 360m
            memory: 562Mi
          limits:
            cpu: 1500m
            memory: 875Mi
      volumes:
      - name: media
        nfs:
          path: /mnt/artemis/data/media
          server: nas1.private.swifthomelab.net
      - name: logs
        emptyDir:
          medium: Memory
          sizeLimit: 100Mi
      - name: var-tmp
        emptyDir:
          medium: Memory
          sizeLimit: 1Gi
  volumeClaimTemplates:
  - metadata:
      name: config
    spec:
      accessModes: [ReadWriteOnce]
      storageClassName: csi-rbd-sc
      resources:
        requests:
          storage: 1Gi
  - metadata:
      name: server
    spec:
      accessModes: [ReadWriteOnce]
      storageClassName: csi-rbd-sc
      resources:
        requests:
          storage: 10Gi
