# yaml-language-server: $schema=https://raw.githubusercontent.com/yannh/kubernetes-json-schema/refs/heads/master/master/statefulset.json
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: tdarr
  labels:
    name: tdarr
    app: tdarr
    app.kubernetes.io/name: tdarr
    app.kubernetes.io/instance: tdarr
  namespace: tdarr
spec:
  selector:
    matchLabels:
      app: tdarr
  serviceName: tdarr
  replicas: 1
  persistentVolumeClaimRetentionPolicy:
    whenDeleted: Retain
    whenScaled: Retain
  template:
    metadata:
      labels:
        app: tdarr
    spec:
      containers:
      - name: tdarr
        image: ghcr.io/haveagitgat/tdarr:2.40.01@sha256:4a9a20b71752eb6f770aba30247b1403e4c9ed2602453ffdd073e9fae25b4dfd
        imagePullPolicy: IfNotPresent
        env:
        - name: S6_READ_ONLY_ROOT
          value: "1"
        - name: UMASK
          value: "0022"
        - name: TZ
          value: Etc/UTC
        - name: PUID
          value: "65534"
        - name: PGID
          value: "65534"
        - name: internalNode
          value: "false"
        - name: nodeID
          value: internal
        ports:
        - containerPort: 8265
          name: ui
        - containerPort: 8266
          name: server
        livenessProbe:
          httpGet:
            path: /api/v2/status
            port: 8266
            scheme: HTTP
          initialDelaySeconds: 60
          failureThreshold: 5
          successThreshold: 1
          timeoutSeconds: 10
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /api/v2/status
            port: 8266
            scheme: HTTP
          initialDelaySeconds: 10
          failureThreshold: 5
          successThreshold: 2
          timeoutSeconds: 5
          periodSeconds: 10
        startupProbe:
          tcpSocket:
            port: 8266
          initialDelaySeconds: 10
          failureThreshold: 60
          successThreshold: 1
          timeoutSeconds: 2
          periodSeconds: 5
        volumeMounts:
        - mountPath: /app/configs
          name: config
        - mountPath: /app/server
          name: server
        - mountPath: /app/logs
          name: logs
        - mountPath: /mnt/media
          name: media
        resources:
          requests:
            cpu: 120m
            memory: 450Mi
          limits:
            cpu: 350m
            memory: 700Mi
      volumes:
      - name: media
        nfs:
          path: /mnt/artemis/data/media
          server: nas1.private.swifthomelab.net
      - name: logs
        emptyDir: {}
  volumeClaimTemplates:
  - metadata:
      name: config
    spec:
      accessModes: [ReadWriteOnce]
      storageClassName: csi-rbd-sc
      resources:
        requests:
          storage: 1Gi
  - metadata:
      name: server
    spec:
      accessModes: [ReadWriteOnce]
      storageClassName: csi-rbd-sc
      resources:
        requests:
          storage: 10Gi
