---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: syncthing
  name: config
  namespace: syncthing
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: 8Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: syncthing
  name: data
  namespace: syncthing
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: 25Gi
