apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: bazarr-swifthomelab-net
  namespace: cert-manager
spec:
  secretName: bazarr-swifthomelab-net
  issuerRef:
    name: swifthomelab-net-issuer
    kind: ClusterIssuer
  commonName: bazarr.swifthomelab.net
  dnsNames:
  - bazarr.swifthomelab.net
