apiVersion: "projectcontour.io/v1"
kind: "HTTPProxy"
metadata:
  name: "bazarr-ingress"
  namespace: "bazarr"
spec:
  virtualhost:
    fqdn: "bazarr.swifthomelab.net"
    tls:
      secretName: "cert-manager/bazarr-swifthomelab-net"
  routes:
    - services:
        - name: "bazarr"
          port: 6767
