apiVersion: apps/v1
kind: "StatefulSet"
metadata:
  name: bazarr
  namespace: bazarr
  labels:
    app: "bazarr"
    app.kubernetes.io/name: "bazarr"
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: bazarr
  persistentVolumeClaimRetentionPolicy:
    whenDeleted: Retain
    whenScaled: Retain
  template:
    metadata:
      labels:
        app: "bazarr"
        app.kubernetes.io/name: "bazarr"
    spec:
      serviceAccountName: default
      terminationGracePeriodSeconds: 60
      securityContext:
        runAsUser: 65534
        runAsGroup: 65534
        fsGroup: 65534
        fsGroupChangePolicy: OnRootMismatch
      containers:
        - name: bazarr
          image: ghcr.io/onedr0p/bazarr:1.4.3@sha256:d2b70813f7d636fb1ab3448e13ca4074630b63216c6c6d02d034cd5d9e938ea3
          ports:
            - name: http
              containerPort: 6767
              protocol: TCP
          volumeMounts:
            - mountPath: /config
              name: bazarr
          livenessProbe:
            httpGet:
              port: 6767
              path: /
              scheme: HTTP
            initialDelaySeconds: 60
            failureThreshold: 5
            successThreshold: 1
            timeoutSeconds: 10
            periodSeconds: 10
          readinessProbe:
            httpGet:
              port: 6767
              path: /
              scheme: HTTP
            initialDelaySeconds: 10
            failureThreshold: 5
            successThreshold: 2
            timeoutSeconds: 5
            periodSeconds: 10
          startupProbe:
            tcpSocket:
              port: 6767
            initialDelaySeconds: 10
            failureThreshold: 60
            successThreshold: 1
            timeoutSeconds: 2
            periodSeconds: 5
          resources:
            requests:
              cpu: 10m
              memory: 50Mi
            limits:
              cpu: 1500m
              memory: 2Gi
          env:
            - name: "UMASK"
              value: "0022"
            - name: "TZ"
              value: "Etc/UTC"
            - name: "BAZARR__PORT"
              value: "6767"
  volumeClaimTemplates:
    - metadata:
        name: bazarr
        labels:
          app.kubernetes.io/part-of: "bazarr"
        namespace: bazarr
      spec:
        storageClassName: proxmox-csi
        accessModes: [ "ReadWriteOncePod" ]
        resources:
          requests:
            storage: 8Gi
