apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: bazarr
  namespace: bazarr
  labels:
    app: bazarr
    app.kubernetes.io/name: bazarr
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: bazarr
  serviceName: bazarr
  persistentVolumeClaimRetentionPolicy:
    whenDeleted: Retain
    whenScaled: Retain
  template:
    metadata:
      labels:
        app: bazarr
        app.kubernetes.io/name: bazarr
    spec:
      serviceAccountName: default
      terminationGracePeriodSeconds: 60
      securityContext:
        runAsUser: 65534
        runAsGroup: 65534
        fsGroup: 65534
        fsGroupChangePolicy: OnRootMismatch
      volumes:
      - name: media
        nfs:
          path: /mnt/artemis/data/media
          server: nas1.private.swifthomelab.net
      containers:
      - name: bazarr
        image: ghcr.io/onedr0p/bazarr:1.4.4@sha256:738abd74a569b91b6fd2fb009b78d11028a0b7bbcb4ea98510afacee8d797c15
        ports:
        - name: http
          containerPort: 6767
          protocol: TCP
        volumeMounts:
        - mountPath: /config
          name: bazarr
        - mountPath: /mnt/media
          name: media
        livenessProbe:
          httpGet:
            port: 6767
            path: /
            scheme: HTTP
          initialDelaySeconds: 60
          failureThreshold: 5
          successThreshold: 1
          timeoutSeconds: 10
          periodSeconds: 10
        readinessProbe:
          httpGet:
            port: 6767
            path: /
            scheme: HTTP
          initialDelaySeconds: 10
          failureThreshold: 5
          successThreshold: 2
          timeoutSeconds: 5
          periodSeconds: 10
        startupProbe:
          tcpSocket:
            port: 6767
          initialDelaySeconds: 10
          failureThreshold: 60
          successThreshold: 1
          timeoutSeconds: 2
          periodSeconds: 5
        resources:
          requests:
            cpu: 10m
            memory: 200Mi
          limits:
            cpu: 1500m
            memory: 1Gi
        env:
        - name: UMASK
          value: "0022"
        - name: TZ
          value: Etc/UTC
        - name: BAZARR__PORT
          value: "6767"
  volumeClaimTemplates:
  - metadata:
      name: bazarr
      labels:
        app.kubernetes.io/part-of: bazarr
      namespace: bazarr
    spec:
      storageClassName: csi-rbd-sc
      accessModes: [ReadWriteOncePod]
      resources:
        requests:
          storage: 8Gi
