# yaml-language-server: $schema=https://raw.githubusercontent.com/yannh/kubernetes-json-schema/refs/heads/master/master/deployment-apps-v1.json
apiVersion: apps/v1
kind: Deployment
metadata:
  name: rss-bridge
  namespace: rss
  labels:
    app.kubernetes.io/name: rss-bridge
    app.kubernetes.io/component: feed-aggregator
    app.kubernetes.io/part-of: rss
  annotations:
    reloader.stakater.com/auto: "true"
spec:
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app.kubernetes.io/name: rss-bridge
      app.kubernetes.io/component: feed-aggregator
      app.kubernetes.io/part-of: rss
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app.kubernetes.io/name: rss-bridge
        app.kubernetes.io/component: feed-aggregator
        app.kubernetes.io/part-of: rss
    spec:
      securityContext:
        fsGroupChangePolicy: OnRootMismatch
        runAsNonRoot: true
        # 33 is www-data on debian
        fsGroup: 33
        runAsGroup: 33
        runAsUser: 33
        sysctls:
        - name: net.ipv4.ip_unprivileged_port_start
          value: "80"
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - topologyKey: kubernetes.io/hostname
            namespaces: []
            namespaceSelector: {}
            labelSelector:
              matchLabels:
                app.kubernetes.io/name: rss-bridge
                app.kubernetes.io/component: feed-aggregator
                app.kubernetes.io/part-of: rss
            matchLabelKeys:
            - pod-template-hash
      containers:
      - name: rss-bridge
        image: docker.io/rssbridge/rss-bridge:latest@sha256:831c29238554805c66b3f4eae136b138ae2e9fe191c76e7ba8d3956138e19bf5
        securityContext:
          allowPrivilegeEscalation: false
          privileged: false
          runAsGroup: 33
          runAsUser: 33
          runAsNonRoot: true
          capabilities:
            drop: [ALL]
            # add: [NET_BIND_SERVICE]
        # resources:
        #   requests:
        #     cpu: ...
        #     memory: ...
        #   limits:
        #     memory: nil
        ports:
        - name: http
          containerPort: 80
          protocol: TCP
        # - name: metrics
        #   containerPort: ...
        #   protocol: TCP
        env:
        - name: TZ
          value: America/Vancouver
        - name: UMASK
          value: "0022"
        volumeMounts:
        - name: tmp
          mountPath: /tmp
        - name: php-run
          mountPath: /run/php
        - name: run
          mountPath: /run
        - name: nginx
          mountPath: /var/lib/nginx
        - name: logs
          mountPath: /var/logs
        - name: app-php
          mountPath: /app/config.ini.php
          subPath: config.ini.php
          readOnly: true
        - name: app-php
          mountPath: /app/bridges/FeedImageBridge.php
          subPath: FeedImageBridge.php
          readOnly: true
        livenessProbe: &probe
          httpGet:
            port: 80
            path: /
        readinessProbe: *probe
        startupProbe: *probe
      volumes:
      - name: run
        emptyDir:
          medium: Memory
      - name: php-run
        emptyDir:
          medium: Memory
      - name: tmp
        emptyDir:
          medium: Memory
      - name: logs
        emptyDir: {}
      - name: nginx
        emptyDir: {}
      - name: app-php
        configMap:
          name: rss-bridge-app-php
          items:
          - key: config.ini.php
            path: config.ini.php
            mode: 0o550
          - key: FeedImageBridge.php
            path: FeedImageBridge.php
            mode: 0o644
