# yaml-language-server: $schema=https://raw.githubusercontent.com/yannh/kubernetes-json-schema/refs/heads/master/master/serviceaccount.json
apiVersion: v1
kind: ServiceAccount
metadata:
  name: plexamp
  labels:
    app.kubernetes.io/name: plexamp
    app.kubernetes.io/instance: plexamp
    app.kubernetes.io/component: media-server
    app.kubernetes.io/part-of: plexamp
  namespace: plexamp
automountServiceAccountToken: false
