# yaml-language-server: $schema=https://json.schemastore.org/chart.json
apiVersion: v2
name: cloudnative-pg
version: 0.1.0

dependencies:
- name: cloudnative-pg
  version: 0.26.1
  repository: https://cloudnative-pg.github.io/charts
