apiVersion: apps/v1
kind: Deployment
metadata:
  name: rustfs
  namespace: rustfs
  labels:
    app.kubernetes.io/name: rustfs
    app.kubernetes.io/instance: rustfs
    app.kubernetes.io/managed-by: Helm
spec:
  template:
    spec:
      containers:
      - name: rustfs
        image: rustfs/rustfs:latest@sha256:f1b59053332cdaa00c6a0d08b43f02fb2d12bf2749098b6d9d5eed693b39b695
      initContainers:
      - name: init-step
        image: busybox:stable@sha256:73aaf090f3d85aa34ee199857f03fa3a95c8ede2ffd4cc2cdb5b94e566b11662
