apiVersion: apps/v1
kind: Deployment
metadata:
  name: rustfs
  namespace: rustfs
  labels:
    app.kubernetes.io/name: rustfs
    app.kubernetes.io/instance: rustfs
    app.kubernetes.io/managed-by: Helm
spec:
  template:
    spec:
      containers:
      - name: rustfs
        image: rustfs/rustfs:latest@sha256:8cc9801755448b71a786705ce76692c77e14936cccd87cf2fc31842e58f4d1ff
      initContainers:
      - name: init-step
        image: busybox:stable@sha256:73aaf090f3d85aa34ee199857f03fa3a95c8ede2ffd4cc2cdb5b94e566b11662
