# yaml-language-server: $schema=https://raw.githubusercontent.com/datreeio/CRDs-catalog/refs/heads/main/projectcontour.io/httpproxy_v1.json
apiVersion: projectcontour.io/v1
kind: HTTPProxy
metadata:
  name: autobrr-ingress
  namespace: autobrr
  labels:
    app.kubernetes.io/name: autobrr
    app.kubernetes.io/instance: autobrr
    app.kubernetes.io/part-of: autobrr
  annotations:
    argocd.argoproj.io/sync-wave: "100"  # needs certs, delegation, services, etc.
spec:
  virtualhost:
    fqdn: autobrr.swifthomelab.net
    tls:
      secretName: cert-manager/autobrr-swifthomelab-net
  routes:
  - services:
    - name: autobrr
      port: 7474
    timeoutPolicy:
      response: 600s  # if NULL, uses 15s (envoy default)
