# yaml-language-server: $schema=https://raw.githubusercontent.com/yannh/kubernetes-json-schema/refs/heads/master/master/statefulset.json
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: autobrr
  namespace: autobrr
  labels:
    app.kubernetes.io/name: autobrr
    app.kubernetes.io/instance: autobrr
    app.kubernetes.io/part-of: autobrr
  annotations:
    argocd.argoproj.io/sync-options: ServerSideApply=true
spec:
  revisionHistoryLimit: 3
  serviceName: autobrr
  selector:
    matchLabels:
      app.kubernetes.io/name: autobrr
      app.kubernetes.io/instance: autobrr
  replicas: 1
  podManagementPolicy: Parallel
  template:
    metadata:
      labels:
        app.kubernetes.io/name: autobrr
        app.kubernetes.io/instance: autobrr
        app.kubernetes.io/part-of: autobrr
    spec:
      restartPolicy: Always
      securityContext:
        fsGroup: 65534
        fsGroupChangePolicy: OnRootMismatch
        runAsGroup: 65534
        runAsUser: 65534
        runAsNonRoot: true
      containers:
      - name: autobrr
        image: ghcr.io/autobrr/autobrr:v1.80.0@sha256:944b1c438302ed10bef810a49f2eb7f334b5abf578db473bcb8d997db3978227
        securityContext:
          allowPrivilegeEscalation: false
          privileged: false
          readOnlyRootFilesystem: true
          runAsGroup: 65534
          runAsUser: 65534
          runAsNonRoot: true
        resources:
          requests:
            cpu: 150m
            memory: 75Mi
          # limits:
          #   memory: nil
        ports:
        - name: http
          containerPort: 7474
          protocol: TCP
        - name: metrics
          containerPort: 9074
          protocol: TCP
        env:
        - name: TZ
          value: America/Vancouver
        - name: UMASK
          value: "0022"
        - name: AUTOBRR__PORT
          value: "7474"
        - name: AUTOBRR__LOG_LEVEL
          value: INFO
        - name: AUTOBRR__DATABASE_TYPE
          value: postgres
        - name: AUTOBRR__DATABASE_DSN
          valueFrom:
            secretKeyRef:
              name: autobrr-dsn
              key: connection-string
              optional: false
        - name: AUTOBRR__METRICS_ENABLED
          value: "true"
        - name: AUTOBRR__METRICS_HOST
          value: 0.0.0.0
        - name: AUTOBRR__METRICS_PORT
          value: "9074"
        volumeMounts:
        - mountPath: /config
          name: config
        - name: tmp
          mountPath: /tmp
        - name: logs
          mountPath: /var/logs
        livenessProbe: &probe
          httpGet:
            port: 7474
            path: /
        readinessProbe: *probe
        startupProbe: *probe
      volumes:
      - name: tmp
        emptyDir: {}
      - name: logs
        emptyDir: {}
  volumeClaimTemplates:
  - apiVersion: v1
    kind: PersistentVolumeClaim
    metadata:
      name: config
      labels:
        app.kubernetes.io/name: autobrr
        app.kubernetes.io/part-of: autobrr
      namespace: autobrr
    spec:
      storageClassName: csi-rbd-sc
      accessModes: [ReadWriteOncePod]
      resources:
        requests:
          storage: 2048Mi
