# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ./resources/upstream.yaml
patches:
- target:
    group: apps
    version: v1
    kind: DaemonSet
    name: fluent-bit
    namespace: fluent-bit
  patch: |-
    - op: add
      path: /spec/template/spec/containers/0/env
      value:
      - name: TZ
        value: America/Vancouver
