kube-prometheus-stack:
  kubeEtcd:
    enabled: true
    service:
      # service managed by kubespray
      # found on namespace `kube-system`
      enabled: false
      port: 2381
      targetPort: 2381
    serviceMonitor:
      enabled: true
  nodeExporter:
    # enables subchart
    enabled: true
  prometheus-node-exporter:
    # subchart options
    service:
      enabled: true
      port: 9100
      targetPort: 9100
    prometheus:
      monitor:
        enabled: true
        scrapeTimeout: 10s
  prometheus:
    prometheusSpec:
      ruleSelectorNilUsesHelmValues: false
      serviceMonitorSelectorNilUsesHelmValues: false
      podMonitorSelectorNilUsesHelmValues: false
      probeSelectorNilUsesHelmValues: false
  cleanPrometheusOperatorObjectNames: true
