apiVersion: "kustomize.config.k8s.io/v1beta1"
kind: "Kustomization"
namespace: "argocd"
resources:
  - "https://raw.githubusercontent.com/argoproj/argo-cd/v2.10.4/manifests/ha/install.yaml"
  - "./base/applications.yaml"
patches:
  - target:
      kind: secret
      name: argocd-initial-admin-secret
      namespace: argocd
    path: "./overlays/argocd-initial-admin-secret.yaml"
