apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ./resources/cert.yaml
- ./resources/httpproxy.yaml
- ./resources/delegation.yaml
patches:
- path: ./overlays/argocd-cmd-params-cm.yaml
  target:
    kind: ConfigMap
    labelSelector: "app.kubernetes.io/name=argocd-cmd-params-cm"
