apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: tautulli-swifthomelab-net
  namespace: cert-manager
spec:
  secretName: tautulli-swifthomelab-net
  issuerRef:
    name: swifthomelab-net-issuer
    kind: ClusterIssuer
  commonName: tautulli.swifthomelab.net
  dnsNames:
  - tautulli.swifthomelab.net
