# yaml-language-server: $schema=https://raw.githubusercontent.com/datreeio/CRDs-catalog/refs/heads/main/projectcontour.io/httpproxy_v1.json
apiVersion: projectcontour.io/v1
kind: HTTPProxy
metadata:
  name: tautulli-ingress
  namespace: tautulli
spec:
  virtualhost:
    fqdn: tautulli.swifthomelab.net
    tls:
      secretName: cert-manager/tautulli-swifthomelab-net
  routes:
  - services:
    - name: tautulli
      port: 80
