# yaml-language-server: $schema=https://raw.githubusercontent.com/yannh/kubernetes-json-schema/refs/heads/master/master/statefulset.json
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: tautulli
  namespace: tautulli
  labels:
    app: tautulli
    app.kubernetes.io/name: tautulli
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app.kubernetes.io/name: tautulli
  serviceName: tautulli
  persistentVolumeClaimRetentionPolicy:
    whenDeleted: Retain
    whenScaled: Retain
  template:
    metadata:
      labels:
        app: tautulli
        app.kubernetes.io/name: tautulli
    spec:
      enableServiceLinks: false
      serviceAccountName: default
      automountServiceAccountToken: true
      securityContext:
        fsGroup: 568
        fsGroupChangePolicy: OnRootMismatch
        runAsGroup: 568
        runAsNonRoot: true
        runAsUser: 568
        seccompProfile:
          type: RuntimeDefault
        sysctls:
        - name: net.ipv4.ip_unprivileged_port_start
          value: "80"
      hostIPC: false
      hostNetwork: false
      hostPID: false
      dnsPolicy: ClusterFirst
      volumes:
      - emptyDir: {}
        name: logs
      - emptyDir: {}
        name: tmp
      containers:
      - name: tautulli
        image: ghcr.io/tautulli/tautulli:v2.16.0@sha256:7e6ede32f7923e01899db906aa6a96d978a4a8df8e2ef0dcf44c92b2d0206221
        args:
        - --config
        - /config/config.ini
        - --datadir
        - /config
        - --port
        - "80"
        command:
        - /usr/local/bin/python
        - Tautulli.py
        ports:
        - name: http
          containerPort: 80
          protocol: TCP
        volumeMounts:
        - mountPath: /config/cache
          name: cache
        - mountPath: /config
          name: config
        - mountPath: /config/logs
          name: logs
        - mountPath: /tmp
          name: tmp
        livenessProbe:
          failureThreshold: 3
          httpGet:
            path: /status
            port: 80
          initialDelaySeconds: 0
          periodSeconds: 10
          timeoutSeconds: 1
        readinessProbe:
          failureThreshold: 3
          httpGet:
            path: /status
            port: 80
          initialDelaySeconds: 0
          periodSeconds: 10
          timeoutSeconds: 1
        resources:
          requests:
            memory: 100Mi
            cpu: 10m
          limits:
            memory: 300Mi
            cpu: 150m
        securityContext:
          capabilities:
            drop:
            - ALL
          readOnlyRootFilesystem: true
        env:
        - name: TZ
          value: America/Los_Angeles
  volumeClaimTemplates:
  - metadata:
      name: config
      labels:
        app.kubernetes.io/part-of: tautulli
      namespace: tautulli
    spec:
      storageClassName: csi-rbd-sc
      accessModes: [ReadWriteOncePod]
      resources:
        requests:
          storage: 5Gi
  - metadata:
      name: cache
      labels:
        app.kubernetes.io/part-of: tautulli
      namespace: tautulli
    spec:
      storageClassName: csi-rbd-sc
      accessModes: [ReadWriteOncePod]
      resources:
        requests:
          storage: 15Gi
