# yaml-language-server: $schema=https://raw.githubusercontent.com/datreeio/CRDs-catalog/refs/heads/main/projectcontour.io/tlscertificatedelegation_v1.json
apiVersion: projectcontour.io/v1
kind: TLSCertificateDelegation
metadata:
  name: ha-swifthomelab-net
  labels:
    app.kubernetes.io/name: home-assistant
    app.kubernetes.io/instance: home-assistant
    app.kubernetes.io/component: home-assistant
    app.kubernetes.io/part-of: home-assistant
  namespace: cert-manager
spec:
  delegations:
  - secretName: ha-swifthomelab-net
    targetNamespaces:
    - home-assistant
