# yaml-language-server: $schema=https://raw.githubusercontent.com/yannh/kubernetes-json-schema/refs/heads/master/master/statefulset.json
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: home-assistant
  labels:
    app.kubernetes.io/name: home-assistant
    app.kubernetes.io/instance: home-assistant
    app.kubernetes.io/component: home-assistant
    app.kubernetes.io/part-of: home-assistant
  namespace: home-assistant
spec:
  serviceName: home-assistant
  selector:
    matchLabels:
      app.kubernetes.io/name: home-assistant
      app.kubernetes.io/instance: home-assistant
  revisionHistoryLimit: 3
  template:
    metadata:
      labels:
        app.kubernetes.io/name: home-assistant
        app.kubernetes.io/instance: home-assistant
        app.kubernetes.io/component: home-assistant
        app.kubernetes.io/part-of: home-assistant
    spec:
      securityContext:
        runAsUser: 65534
        runAsGroup: 65534
        fsGroup: 65534
        fsGroupChangePolicy: OnRootMismatch
      terminationGracePeriodSeconds: 90
      containers:
      - name: home-assistant
        image: ghcr.io/home-operations/home-assistant:2025.11.1@sha256:36619b3746910f9b3d21e02c4e8090b837be4bacf88987755d09988cec2dfb1f
        ports:
        - containerPort: 8123
          name: http
        resources: {}
        volumeMounts:
        - name: config
          mountPath: /config
        readinessProbe:
          failureThreshold: 3
          httpGet:
            path: /manifest.json
            port: 8123
          initialDelaySeconds: 3
          periodSeconds: 10
          timeoutSeconds: 1
  volumeClaimTemplates:
  - metadata:
      name: config
    spec:
      accessModes: [ReadWriteOnce]
      storageClassName: csi-rbd-sc
      resources:
        requests:
          storage: 15Gi
