# yaml-language-server: $schema=https://json.schemastore.org/chart.json
apiVersion: v2
name: ceph-csi-rbd
description: Container Storage Interface (CSI) driver, provisioner, snapshotter, resizer and attacher for Ceph RBD
type: application

# this version number should be incremented each time you make changes
# to the chart and its templates, including the app version.
# is expected to follow semantic versioning!
version: 1.0.0

# this is the version number of the application being deployed
# should be incremented each time you make changes to the application
appVersion: "1.0"

dependencies:
- name: ceph-csi-rbd
  version: 3.16.0
  repository: https://ceph.github.io/csi-charts
