apiVersion: "cert-manager.io/v1"
kind: "Certificate"
metadata:
  name: "influxdb2-swifthomelab-net"
  namespace: "cert-manager"
spec:
  secretName: "influxdb2-swifthomelab-net"
  issuerRef:
    name: "swifthomelab-net-issuer"
    kind: "ClusterIssuer"
  commonName: "influxdb2.swifthomelab.net"
  dnsNames:
    - "influxdb2.swifthomelab.net"
