apiVersion: "projectcontour.io/v1"
kind: "TLSCertificateDelegation"
metadata:
  name: "influxdb2-swifthomelab-net"
  namespace: "cert-manager"
spec:
  delegations:
    - secretName: "influxdb2-swifthomelab-net"
      targetNamespaces:
        - "influxdb"
