apiVersion: "projectcontour.io/v1"
kind: "HTTPProxy"
metadata:
  name: "influxdb2-ingress"
  namespace: "influxdb"
spec:
  virtualhost:
    fqdn: "influxdb2.swifthomelab.net"
    tls:
      secretName: "cert-manager/influxdb2-swifthomelab-net"
  routes:
    - conditions:
        - prefix: "/"
      services:
        - name: "influxdb2"
          port: 80
