influxdb2:
  image:
    repository: influxdb
    tag: 2.7.7-alpine@sha256:c0eb6d9abd89dee9efc9f55e9ad81acb9db6db87e882667456a279ab7d61e25d
    pullPolicy: IfNotPresent
  livenessProbe:
    path: /health
    scheme: HTTP
    initialDelaySeconds: 0
    periodSeconds: 10
    timeoutSeconds: 1
    failureThreshold: 3
  readinessProbe:
    path: /health
    scheme: HTTP
    initialDelaySeconds: 0
    periodSeconds: 10
    timeoutSeconds: 1
    successThreshold: 1
    failureThreshold: 3
  startupProbe:
    enabled: true
    path: /health
    scheme: HTTP
    initialDelaySeconds: 30
    periodSeconds: 5
    timeoutSeconds: 1
    failureThreshold: 6
  adminUser:
    organization: influxdata
    bucket: default
    user: admin
    retention_policy: 0s
    ## Leave empty to generate a random password and token.
    ## Or fill any of these values to use fixed values.
    password: ""
    token: ""
    ## The password and token are obtained from an existing secret. The expected
    ## keys are `admin-password` and `admin-token`.
    ## If set, the password and token values above are ignored.
    existingSecret: influxdb-auth
  persistence:
    enabled: true
    storageClass: proxmox-csi
    accessMode: ReadWriteOnce
    size: 50Gi
    mountPath: /var/lib/influxdb2
  initScripts:
    enabled: false
  service:
    type: ClusterIP
    port: 80
    targetPort: 8086
    portName: http
  ingress:
    enabled: false
  pdb:
    create: false
