apiVersion: "argoproj.io/v1alpha1"
kind: "Application"
metadata:
  name: "longhorn"
  namespace: "argocd"
  finalizers:
    - "resources-finalizer.argocd.argoproj.io"
spec:
  destination:
    namespace: "longhorn-system"
    server: "https://kubernetes.default.svc"
  project: "default"
  source:
    path: "longhorn"
    repoURL: "https://github.com/JosBritton/cd.git"
    targetRevision: "HEAD"
  syncPolicy:
    syncOptions:
      - "CreateNamespace=true"
