# yaml-language-server: $schema=https://json.schemastore.org/chart.json
apiVersion: v2
name: cert-manager
version: 0.1.0

dependencies:
- name: cert-manager
  version: v1.18.0
  repository: https://charts.jetstack.io
