descheduler:
  kind: CronJob
  deschedulerPolicy:
    profiles:
    - name: default
      pluginConfig:
      - name: DefaultEvictor
        args:
          evictFailedBarePods: true
          evictLocalStoragePods: true
          evictSystemCriticalPods: true
          nodeFit: true
      - name: RemovePodsViolatingInterPodAntiAffinity
      - name: RemovePodsViolatingNodeAffinity
        args:
          nodeAffinityType:
          - requiredDuringSchedulingIgnoredDuringExecution
      - name: RemovePodsViolatingNodeTaints
      - name: RemovePodsViolatingTopologySpreadConstraint
        args:
          constraints:
          - DoNotSchedule
          - ScheduleAnyway
      - name: RemoveDuplicates
      - name: RemovePodsHavingTooManyRestarts
        args:
          podRestartThreshold: 100
          includingInitContainers: true
      - name: RemovePodsViolatingNodeTaints
      - name: RemovePodsViolatingInterPodAntiAffinity
      - name: RemovePodsViolatingTopologySpreadConstraint
      - name: LowNodeUtilization
        args:
          thresholds:
            cpu: 20
            memory: 20
            pods: 20
          targetThresholds:
            cpu: 50
            memory: 50
            pods: 50
      plugins:
        balance:
          enabled:
          - RemoveDuplicates
          - RemovePodsViolatingTopologySpreadConstraint
          - LowNodeUtilization
        deschedule:
          enabled:
          - RemovePodsHavingTooManyRestarts
          - RemovePodsViolatingNodeTaints
          - RemovePodsViolatingNodeAffinity
          - RemovePodsViolatingInterPodAntiAffinity
