# yaml-language-server: $schema=https://json.schemastore.org/chart.json
apiVersion: v2
name: victoria-logs
version: 0.1.0

dependencies:
- name: victoria-logs-single
  version: 0.13.9
  repository: oci://ghcr.io/victoriametrics/helm-charts
