---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: syncthing
  name: syncthing
  namespace: syncthing
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: 25Gi
