contour:
  envoy:
    service:
      type: NodePort
      nodePorts:
        http: 30080
        https: 30443
    resources:
      requests:
        cpu: 10m
        ephemeral-storage: 50Mi
        memory: 200Mi
      limits:
        cpu: 200m
        ephemeral-storage: 2Gi
        memory: 800Mi
    shutdownManager:
      resourcesPreset: nano
  contour:
    resources:
      requests:
        cpu: 10m
        ephemeral-storage: 50Mi
        memory: 90Mi
      limits:
        cpu: 80m
        ephemeral-storage: 2Gi
        memory: 180Mi
  defaultBackend:
    enabled: false
