contour:
  configInline:
    serverHeaderTransformation: pass_through  # do not add envoy server header to requests
  envoy:
    service:
      type: NodePort
      nodePorts:
        http: 30080
        https: 30443
    resources:
      requests:
        cpu: 10m
        ephemeral-storage: 50Mi
        memory: 400Mi
      limits:
        cpu: 200m
        ephemeral-storage: 2Gi
        memory: 1500Mi
    shutdownManager:
      resourcesPreset: nano
  contour:
    resources:
      requests:
        cpu: 10m
        ephemeral-storage: 50Mi
        memory: 90Mi
      limits:
        cpu: 80m
        ephemeral-storage: 2Gi
        memory: 180Mi
  defaultBackend:
    enabled: false
