# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ./resources/upstream.yaml
- ./resources/argocd-metrics-servicemonitor.yaml
- ./resources/argocd-server-metrics-servicemonitor.yaml
- ./resources/argocd-repo-server-metrics-servicemonitor.yaml
- ./resources/argocd-notifications-controller-metrics-servicemonitor.yaml
- ./resources/cert.yaml
- ./resources/httpproxy.yaml
- ./resources/delegation.yaml
- ./resources/stork-agent-service-bind.yaml
- ./resources/stork-agent-endpoints-bind.yaml
- ./resources/stork-agent-servicemonitor-bind.yaml
# yamllint disable-line rule:comments
- github.com/dotdc/grafana-dashboards-kubernetes?ref=e24cf83f10669ccc6473b61eb981de2c639df7cb # tag=v2.8.1
generatorOptions:
  disableNameSuffixHash: true
  labels:
    grafana_dashboard: "1"
configMapGenerator:
- name: argocd-dashboard-cm
  files: [files/argocd-dashboard.json]
- name: proxmox-dashboard-cm
  files: [files/proxmox-cluster-dashboard.json]
- name: bind9-resolver-dashboard-cm
  files: [files/bind9-resolver.json]
patches:
- path: overlays/prometheus-operator-grafana-secret.yaml
- path: overlays/prometheus-crds-annotations.yaml
  target:
    group: apiextensions.k8s.io
    kind: CustomResourceDefinition
    name: .*
    version: v1
- path: overlays/prometheus-operator-grafana-cm.yaml
- target:
    name: .*
    version: v1
    kind: ConfigMap
    labelSelector: app.kubernetes.io/part-of=kube-prometheus-stack,grafana_dashboard=1
  patch: |-
    - op: add
      path: /metadata/annotations/grafana_folder
      value: Cluster
- target:
    name: dashboards\-k8s\-.*
    version: v1
    kind: ConfigMap
    labelSelector: grafana_dashboard=1
  patch: |-
    - op: replace
      path: /metadata/annotations/grafana_folder
      value: Cluster
- target:
    name: argocd-dashboard-cm
    version: v1
    kind: ConfigMap
    labelSelector: grafana_dashboard=1
  patch: |-
    - op: replace
      path: /metadata/annotations/grafana_folder
      value: Cluster
# delete trivy dashboard
- path: overlays/dashboards-k8s-addons-trivy-operator-cm.yaml
# delete macos node exporter dashboard
- path: overlays/prometheus-operator-kube-p-nodes-darwin-cm.yaml
