apiVersion: "projectcontour.io/v1"
kind: "HTTPProxy"
metadata:
  name: "argocd-ingress"
  namespace: "argocd"
spec:
  virtualhost:
    fqdn: "argocd.swifthomelab.net"
    tls:
      secretName: "cert-manager/argocd-swifthomelab-net"
  routes:
    - services:
        - name: "argocd-server"
          port: 80
