rustfs:
  secret:
    existingSecret: rustfs-secret
  mode:
    standalone:
      enabled: true
    distributed:
      enabled: false
  ingress:
    enabled: false
  storageclass:
    name: csi-rbd-sc
    dataStorageSize: 4096Mi
    logStorageSize: 512Mi
  config:
    rustfs:
      log_rotation:
        size: 20
        time: hour
        keep_files: 10
