rustfs:
  secret:
    existingSecret: rustfs-secret
  mode:
    standalone:
      enabled: true
    distributed:
      enabled: false
  ingress:
    enabled: false
  storageclass:
    name: csi-rbd-sc
    dataStorageSize: 256Mi
    logStorageSize: 256Mi
