apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: proxmox-csi
  # storageclass.kubernetes.io/is-default-class: true
parameters:
  csi.storage.k8s.io/fstype: ext4
  cache: none
  ssd: "true"
  storage: tank
provisioner: csi.proxmox.sinextra.dev
allowVolumeExpansion: true
reclaimPolicy: Delete
volumeBindingMode: WaitForFirstConsumer
mountOptions:
- noatime
