apiVersion: "v1"
kind: "PersistentVolumeClaim"
metadata:
  labels:
    app: "vaultwarden"
  name: "vaultwarden"
  namespace: "vaultwarden"
spec:
  accessModes:
    - "ReadWriteOnce"
  storageClassName: "longhorn"
  resources:
    requests:
      storage: "2Gi"
