# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: reloader
resources:
# yamllint disable-line rule:comments
- github.com/stakater/Reloader/deployments/kubernetes?ref=81789fd7d0493f60a53b7324085b7e5ed5ce008b # tag=v1.4.17
patches:
- target:
    group: apps
    version: v1
    kind: Deployment
  patch: |-
    - op: replace
      path: /spec/template/spec/containers/0/resources
      value:
        limits:
          memory: 512Mi
        requests:
          cpu: 10m
          memory: 128Mi
- path: ./overlays/image.yaml
