name: Validate Manifests
on:  # yamllint disable-line rule:truthy
  push: {}
  pull_request:
    branches:
    - master
permissions:
  contents: read
jobs:
  lint-yaml:
    runs-on: ubuntu-latest
    steps:
    - name: Code Checkout
      uses: actions/checkout@v3
    - name: Validate YAML
      uses: ibiqlik/action-yamllint@v3
      with:
        format: github
  lint-kustomize:
    runs-on: ubuntu-latest
    steps:
    - name: Code Checkout
      uses: actions/checkout@v3
    - name: Verify Kustomize CLI Installation
      run: |
        which kustomize
        kustomize version
    - name: Validate Manifests
      run: |
        make validate
