name: Validate Manifests
on:  # yamllint disable-line rule:truthy
  push: {}
  pull_request:
    branches:
    - master
permissions:
  contents: read
jobs:
  lint-yaml:
    runs-on: ubuntu-latest
    steps:
    - name: Code Checkout
      uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4
    - name: Validate YAML
      uses: ibiqlik/action-yamllint@2576378a8e339169678f9939646ee3ee325e845c # v3
      with:
        format: github
  validate-templates:
    runs-on: ubuntu-latest
    steps:
    - name: Code Checkout
      uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4
    - name: Setup Go environment
      uses: actions/setup-go@v5.0.2
      with:
        go-version: 1.22.5
    - name: Install kubeconform
      run: |
        go install github.com/yannh/kubeconform/cmd/kubeconform@v0.6.6
    - name: Validate Manifests
      run: |
        make validate
