# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
# yamllint disable rule:comments
name: Validate Manifests
on: # yamllint disable-line rule:truthy
  push: {}
permissions:
  contents: read
jobs:
  lint:
    name: Lint yaml
    runs-on: ubuntu-latest
    steps:
    - name: Code Checkout
      uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
    - name: Run yamllint
      uses: ibiqlik/action-yamllint@2576378a8e339169678f9939646ee3ee325e845c # v3.1.1
      with:
        file_or_dir: .
        format: github  # OUTPUT format (github=fancy github output)

  helm:
    name: Render helm chart templates
    runs-on: ubuntu-latest
    steps:
    - name: Code Checkout
      uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
    - name: Render helm chart templates
      run: |
        parallel -j0 "helm dependency update "{//}" && helm template --include-crds --namespace testns -- testchart "{//}"" ::: "$(find apps/ -regex ".*/upstream/Chart.ya?ml")"

  kustomize:
    name: Build kustomization files
    runs-on: ubuntu-latest
    steps:
    - name: Code Checkout
      uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
    - name: Build kustomize files
      run: |
        parallel -j0 "kustomize build "{//}"" ::: "$(find apps/ -name kustomization.yaml)" bootstrap/argo-cd/kustomization.yaml

  kubeconform:
    name: Validate kubernetes manifests
    runs-on: ubuntu-latest
    steps:
    - name: Code Checkout
      uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
    - name: Setup Go environment
      uses: actions/setup-go@d35c59abb061a4a6fb18e82ac0862c26744d6ab5 # v5.5.0
      with:
        go-version: stable
        cache: false  # no deps to cache
    - name: Install kubeconform
      run: |
        go install github.com/yannh/kubeconform/cmd/kubeconform@latest
    - name: Generate cache key
      id: generate-cache-key
      run: |
        datree_sha="$(curl -s -H 'Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}' \
          -H "Accept: application/vnd.github.VERSION.sha" \
          "${GITHUB_API_URL}/repos/datreeio/CRDs-catalog/commits/main")"

        schemastore_sha="$(curl -s -H 'Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}' \
          -H "Accept: application/vnd.github.VERSION.sha" \
          "${GITHUB_API_URL}/repos/schemastore/schemastore/commits/master")"

        echo "key=$(echo -n "$datree_sha$schemastore_sha" | md5sum | cut -c 1-7)" >> "$GITHUB_OUTPUT"
    - name: Restore cached schemas
      id: cache-kubeconform-restore
      uses: actions/cache/restore@0057852bfaa89a56745cba8c7296529d2fc39830 # v4.3.0
      with:
        fail-on-cache-miss: false
        path: |
          ${{ github.workspace }}/.cache/kubeconform
        key: kubeconform-schemas-${{ steps.generate-cache-key.outputs.key }}
    - name: Get cached schemas
      if: steps.cache-kubeconform-restore.outputs.cache-hit == 'true'
      run: |
        ls -R "$GITHUB_WORKSPACE/.cache/kubeconform"
    - name: Validate manifests with kubeconform
      run: |
        mkdir -p "$GITHUB_WORKSPACE/.cache/kubeconform"

        kubeconform \
          -n "$(nproc)" \
          --cache "$GITHUB_WORKSPACE/.cache/kubeconform" \
          --skip CustomResourceDefinition \
          --ignore-filename-pattern "apps/.*/upstream/.*\.ya?ml" \
          --ignore-filename-pattern "apps/.*/files/.*\.ya?ml" \
          --ignore-filename-pattern "apps/.*/overlays/.*\.ya?ml" \
          --ignore-filename-pattern "/.*\.json" \
          --schema-location default \
          --schema-location "https://raw.githubusercontent.com/datreeio/CRDs-catalog/main/{{.Group}}/{{.ResourceKind}}_{{.ResourceAPIVersion}}.json" \
          --schema-location "https://json.schemastore.org/{{.ResourceKind}}.json" \
          --summary \
          --strict \
          --verbose \
          -- apps/
    - name: Cache schemas
      id: cache-kubeconform-save
      if: steps.cache-kubeconform-restore.outputs.cache-hit != 'true'
      uses: actions/cache/save@0057852bfaa89a56745cba8c7296529d2fc39830 # v4.3.0
      with:
        path: |
          ${{ github.workspace }}/.cache/kubeconform
        key: kubeconform-schemas-${{ steps.generate-cache-key.outputs.key }}
