name: Validate Manifests
on:  # yamllint disable-line rule:truthy
  push: {}
  pull_request:
    branches:
    - master
permissions:
  contents: read
jobs:
  lint-yaml:
    runs-on: ubuntu-latest
    steps:
    - name: Code Checkout
      uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # v3
    - name: Validate YAML
      uses: ibiqlik/action-yamllint@2576378a8e339169678f9939646ee3ee325e845c # v3
      with:
        format: github
  validate-templates:
    runs-on: ubuntu-latest
    steps:
    - name: Code Checkout
      uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # v3
    - name: Validate Manifests
      run: |
        make validate-ci
