# yamllint disable rule:comments
name: Validate Manifests
on:
  push: {}
permissions:
  contents: read
jobs:
  lint-yaml:
    runs-on: ubuntu-latest
    steps:
    - name: Code Checkout
      uses: actions/checkout@eef61447b9ff4aafe5dcd4e0bbf5d482be7e7871 # v4
    - name: Validate YAML
      uses: ibiqlik/action-yamllint@2576378a8e339169678f9939646ee3ee325e845c # v3
      with:
        format: github
  validate-templates:
    runs-on: ubuntu-latest
    steps:
    - name: Code Checkout
      uses: actions/checkout@eef61447b9ff4aafe5dcd4e0bbf5d482be7e7871 # v4
    - name: Setup Go environment
      uses: actions/setup-go@0a12ed9d6a96ab950c8f026ed9f722fe0da7ef32 # v5.0.2
      with:
        go-version: 1.22.5
    - name: Install kubeconform
      run: |
        go install github.com/yannh/kubeconform/cmd/kubeconform@v0.6.6
    - name: Validate Manifests
      run: |
        make validate
