# yaml-language-server: $schema=https://raw.githubusercontent.com/yannh/kubernetes-json-schema/refs/heads/master/master/serviceaccount.json
apiVersion: v1
kind: ServiceAccount
metadata:
  name: plex-media-server
  labels:
    app: plex-media-server
    app.kubernetes.io/name: plex-media-server
    app.kubernetes.io/instance: plex-media-server
  namespace: plex-media-server
automountServiceAccountToken: false
