# yaml-language-server: $schema=https://raw.githubusercontent.com/yannh/kubernetes-json-schema/refs/heads/master/master/statefulset.json
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: plex-media-server
  labels:
    name: plex-media-server
    app: plex-media-server
    app.kubernetes.io/name: plex-media-server
    app.kubernetes.io/instance: plex-media-server
  namespace: plex-media-server
spec:
  serviceName: plex-media-server
  selector:
    matchLabels:
      app.kubernetes.io/name: plex-media-server
      app.kubernetes.io/instance: plex-media-server
  revisionHistoryLimit: 3
  template:
    metadata:
      labels:
        app: plex-media-server
        app.kubernetes.io/name: plex-media-server
        app.kubernetes.io/instance: plex-media-server
    spec:
      securityContext:
        runAsUser: 65534
        runAsGroup: 65534
        fsGroup: 65534
        fsGroupChangePolicy: OnRootMismatch
      serviceAccountName: plex-media-server
      volumes:
      - name: pms-transcode
        emptyDir: {}
      - name: pms-logs
        emptyDir: {}
      - name: movies
        nfs:
          path: /mnt/artemis/data/media/movies
          server: nas1.private.swifthomelab.net
      - name: tv
        nfs:
          path: /mnt/artemis/data/media/tv
          server: nas1.private.swifthomelab.net
      - name: music
        nfs:
          path: /mnt/artemis/data/media/music
          server: nas1.private.swifthomelab.net
      terminationGracePeriodSeconds: 120
      containers:
      - name: plex-media-server-pms
        image: ghcr.io/home-operations/plex:1.41.9.9961@sha256:6c86319bb3275135f5da5aec71b45e48305669ecbceee0f88d335bebf0d0f218
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 32400
          name: pms
        env:
        - name: ALLOWED_NETWORKS
          value: 10.0.8.0/22
        - name: HOSTNAME
          value: PlexServer
        - name: PLEX_GID
          value: "1000"
        - name: PLEX_UID
          value: "1000"
        - name: TZ
          value: Etc/UTC
        resources:
          requests:
            cpu: 4000m
            memory: 1500Mi
          limits:
            cpu: 8500m
            memory: 5Gi
        volumeMounts:
        - name: pms-config
          mountPath: /config
        - name: pms-transcode
          mountPath: /transcode
        - mountPath: /music
          name: music
        - mountPath: /movies
          name: movies
        - mountPath: /tv
          name: tv
        - mountPath: /config/Library/Application Support/Plex Media Server/Logs
          name: pms-logs
        - mountPath: /config/Library/Application Support/Plex Media Server/Cache
          name: pms-cache
  volumeClaimTemplates:
  - metadata:
      name: pms-config
    spec:
      accessModes: [ReadWriteOnce]
      storageClassName: csi-rbd-sc
      resources:
        requests:
          storage: 50Gi
  - metadata:
      name: pms-cache
    spec:
      accessModes: [ReadWriteOnce]
      storageClassName: csi-rbd-sc
      resources:
        requests:
          storage: 25Gi
