# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ./resources/upstream.yaml
- ./resources/cert.yaml
- ./resources/delegation.yaml
- ./resources/httpproxy.yaml
patches:
- target:
    group: apps
    version: v1
    kind: Deployment
    name: gitea
    namespace: gitea
  patch: |-
    - op: replace
      path: /spec/revisionHistoryLimit
      value: 2
# delete gitea secret
- path: overlays/gitea.yaml
- path: overlays/gitea-init.yaml
- path: overlays/gitea-inline-config.yaml
